SELECT  E.NOMBRE,EV.NOMBRE FROM SCOREBOARD S ,EQUIPOS E , EVENTOS EV  WHERE S.EQUIPO = E.ID_EQUIPO AND S.ID_EVENTO =  EV.ID_EVENTO ORDER BY PROBLEMAS_RESUELTOS DESC,EV.NOMBRE;

SELECT VALOR, E.NOMBRE FROM (SELECT SUM(VALOR) AS VALOR, I.EVENTO AS EVE FROM INSCRIPCIONES I   GROUP BY I.EVENTO)  CON, EVENTOS E WHERE CON.EVE = E.ID_EVENTO ORDER BY VALOR DESC;

SELECT S.PROBLEMAS_RESUELTOS, E.NOMBRE , EV.NOMBRE FROM SCOREBOARD S, EQUIPOS E, EVENTOS EV WHERE S.ID_EVENTO = 1 AND S.EQUIPO = E.ID_EQUIPO AND EV.ID_EVENTO = S.ID_EVENTO;

SELECT * FROM EVENTOS E WHERE E.CLASE = 'Conferencia';  

SELECT * FROM EVENTOS E WHERE E.Nivel = 'Dificil' and FECHAFIN IS NULL;  

SELECT * FROM EVENTOS E WHERE FECHAFIN IS NULL ORDER BY COSTO ASC;

SELECT  P.NOMBRE,P.ID_PROBLEMA FROM EVENTOS E , TIENE T , PROBLEMAS P  WHERE E.ID_EVENTO  = T.ID_EVENTO AND T.ID_PROBLEMA  = P.ID_PROBLEMA AND E.ID_EVENTO = 6 ;