CREATE OR REPLACE PACKAGE PC_DONACIONES IS
    PROCEDURE AD_DONACION(xdonante IN INTEGER);
    PROCEDURE AD_CONTIENE(xdonacion IN INTEGER, xproducto IN INTEGER, xcantidad IN INTEGER);

    FUNCTION CO_DONANTES RETURN SYS_REFCURSOR;
END PC_DONACIONES;
/

CREATE OR REPLACE PACKAGE PC_SUCURSAL IS
    PROCEDURE AD_CADENA(xnombre IN VARCHAR);
    PROCEDURE MO_CADENA(xidCadena IN INTEGER, xnombre IN VARCHAR);
    PROCEDURE AD_SUCURSAL(xcadena IN INTEGER, xlocalidad IN VARCHAR, xbarrio IN VARCHAR, xdireccion IN VARCHAR);
    PROCEDURE MO_SUCURSAL(xidSucursal IN INTEGER, xlocalidad IN VARCHAR, xbarrio IN VARCHAR, xdireccion IN VARCHAR);
    PROCEDURE EL_SUCURSAL(xidSucursal IN INTEGER);

    FUNCTION CO_SUCURSALES RETURN SYS_REFCURSOR;
END PC_SUCURSAL;
/

CREATE OR REPLACE PACKAGE PC_PRODUCTO IS
    PROCEDURE AD_PRODUCTO(xfabricante IN VARCHAR, xnombre IN VARCHAR, xprecio IN NUMBER, xfechaVencimiento IN DATE);
    PROCEDURE MO_PRODUCTO(xidProducto IN INTEGER, xprecio IN NUMBER);
    PROCEDURE EL_PRODUCTO(xidProducto IN INTEGER);
    PROCEDURE AD_PROMOCION(xidProducto IN INTEGER, xfInicio IN VARCHAR, xfFinal IN VARCHAR, xdescuento IN NUMBER);
    PROCEDURE MO_PROMOCION(xidPromocion IN INTEGER, xfFinal IN DATE);

    FUNCTION CO_PROMOCIONES RETURN SYS_REFCURSOR;
END PC_PRODUCTO;
/

CREATE OR REPLACE PACKAGE PC_CLIENTE IS
    PROCEDURE AD_CLIENTE(xtipoDocumento IN VARCHAR, xnDocumento IN INTEGER, xnombre IN VARCHAR);
    PROCEDURE MO_CLIENTE(xidCliente  IN  INTEGER, xtipoDocumento IN VARCHAR, xnDocumento IN INTEGER, xnombre IN VARCHAR);
    PROCEDURE EL_CLIENTE(xidCliente IN INTEGER);
    PROCEDURE AD_DESEO(xcliente IN INTEGER, xproducto IN INTEGER);
    PROCEDURE EL_DESEO(xcliente IN INTEGER, xproducto IN INTEGER);

    FUNCTION CO_LISTADESEOS(xidCliente IN INTEGER) RETURN SYS_REFCURSOR;
END PC_CLIENTE;
/