/*fk*/

ALTER TABLE veredictos ADD CONSTRAINT FK_VEREDICTOS_USUARIOS
 FOREIGN KEY (USUARIO) REFERENCES USUARIOS(USERNAME);


ALTER TABLE veredictos ADD CONSTRAINT FK_VEREDICTOS_PROBLEMAS
 FOREIGN KEY (PROBLEMA) REFERENCES PROBLEMAS(ID_PROBLEMA);

ALTER TABLE VEREDICTOS ADD CONSTRAINT FK_VEREDICTOS_ENVIOS
 FOREIGN KEY (ENVIO) REFERENCES ENVIOS(ID_ENVIO);


ALTER TABLE TIENE ADD CONSTRAINT FK_TIENE_EVENTOS
 FOREIGN KEY (ID_EVENTO) REFERENCES EVENTOS(ID_EVENTO);

ALTER TABLE TIENE ADD CONSTRAINT FK_TIENE_PROBLEMAS
 FOREIGN KEY (ID_PROBLEMA) REFERENCES PROBLEMAS(ID_PROBLEMA);


ALTER TABLE SCOREBOARD ADD CONSTRAINT FK_SCOREBOARD_EVENTOS
 FOREIGN KEY (ID_EVENTO) REFERENCES EVENTOS(ID_EVENTO);

ALTER TABLE SCOREBOARD ADD CONSTRAINT FK_SCOREBOARD_EQUIPO
 FOREIGN KEY (EQUIPO) REFERENCES EQUIPOS(ID_EQUIPO);


ALTER TABLE ASOCIACIONES ADD CONSTRAINT FK_ASOCIACIONES_LUGAR
 FOREIGN KEY (LUGAR) REFERENCES LUGARES(ID_LUGAR);

ALTER TABLE REALIZAN ADD CONSTRAINT FK_REALIZAN_ASOCIACION
 FOREIGN KEY (ID_ASOCIACION) REFERENCES ASOCIACIONES(ID_ASOCIACION);
 
ALTER TABLE REALIZAN ADD CONSTRAINT FK_REALIZAN_EVENTOS
 FOREIGN KEY (ID_EVENTO) REFERENCES EVENTOS(ID_EVENTO);


ALTER TABLE ENVIOS ADD CONSTRAINT FK_ENVIOS_PROBLEMAS
 FOREIGN KEY (PROBLEMA) REFERENCES PROBLEMAS(ID_PROBLEMA); 

ALTER TABLE ENVIOS ADD CONSTRAINT FK_ENVIOS_EQUIPOS
 FOREIGN KEY (EQUIPO) REFERENCES EQUIPOS(ID_EQUIPO); 

ALTER TABLE ENVIOS ADD CONSTRAINT FK_ENVIOS_EVENTOS
 FOREIGN KEY (EVENTO) REFERENCES EVENTOS(ID_EVENTO); 


ALTER TABLE ASISTE ADD CONSTRAINT FK_ASISTE_EVENTOS
 FOREIGN KEY (EVENTO) REFERENCES EVENTOS(ID_EVENTO); 

ALTER TABLE ASISTE ADD CONSTRAINT FK_ASISTE_EQUIPOS
 FOREIGN KEY (EQUIPO) REFERENCES EQUIPOS(ID_EQUIPO); 
 
 
ALTER TABLE INSCRIPCIONES ADD CONSTRAINT FK_INSCRIPCIONES_EQUIPOS
 FOREIGN KEY (EQUIPO) REFERENCES EQUIPOS(ID_EQUIPO); 

ALTER TABLE INSCRIPCIONES ADD CONSTRAINT FK_INSCRIPCIONES_EVENTOS
 FOREIGN KEY (EVENTO) REFERENCES EVENTOS(ID_EVENTO); 

ALTER TABLE EVENTOS ADD CONSTRAINT FK_EVENTOS_LUGAR
 FOREIGN KEY (LUGAR) REFERENCES LUGARES(ID_LUGAR); 

