CREATE OR REPLACE PACKAGE PC_COMENTARIOS IS 
  /*COMENTARIOS*/
  PROCEDURE AD_COMENTARIOS (xID_COMENTARIO IN NUMBER, xEXPLICACION  IN VARCHAR,xFECHA IN DATE,xGRUPO IN NUMBER,xUSUARIO  IN VARCHAR,xPROBLEMA  IN  NUMBER,xID_COMENTARIO_RESPUESTA IN NUMBER);
  FUNCTION CO_COMENTARIOS  RETURN SYS_REFCURSOR;
  
  FUNCTION CO_CO4(xTest IN VARCHAR) RETURN SYS_REFCURSOR;
  FUNCTION CO_CO5(xTest IN NUMBER) RETURN SYS_REFCURSOR;

END PC_COMENTARIOS;

CREATE OR REPLACE PACKAGE BODY PC_COMENTARIOS IS 

	PROCEDURE AD_COMENTARIOS(xID_COMENTARIO IN NUMBER, xEXPLICACION  IN VARCHAR,xFECHA IN DATE,xGRUPO IN NUMBER,xUSUARIO  IN VARCHAR,xPROBLEMA  IN  NUMBER,xID_COMENTARIO_RESPUESTA IN NUMBER) IS 
		BEGIN
		  INSERT INTO  COMENTARIOS(ID_COMENTARIO,EXPLICACION,FECHA,GRUPO,USUARIO,PROBLEMA,ID_COMENTARIO_RESPUESTA) VALUES(xID_COMENTARIO,xEXPLICACION,xFECHA,xGRUPO,xUSUARIO,xPROBLEMA,xID_COMENTARIO_RESPUESTA);
		  COMMIT;
		  EXCEPTION 
		  WHEN OTHERS THEN
			ROLLBACK;
			RAISE_APPLICATION_ERROR(-20010, 'No se puede insertar en usuarios.');
		END;

	FUNCTION CO_COMENTARIOS  RETURN SYS_REFCURSOR IS CO_CO SYS_REFCURSOR;
		BEGIN
		OPEN CO_CO  FOR
			SELECT * FROM COMENTARIOS;
		RETURN CO_CO;
	END;
	
	
	FUNCTION CO_CO4(xTest IN VARCHAR)  RETURN SYS_REFCURSOR IS CO_CON4 SYS_REFCURSOR;
		BEGIN
		OPEN CO_CON4  FOR
			SELECT DISTINCT * FROM COMENTARIOS C,PROBLEMAS P
				WHERE ID_PROBLEMA = PROBLEMA AND CREADOR <>xTest AND USUARIO= xTest;
		RETURN CO_CON4;
	END;
	
	FUNCTION CO_CO5(xTest IN NUMBER)  RETURN SYS_REFCURSOR IS CO_CON5 SYS_REFCURSOR;
		BEGIN
		OPEN CO_CON5  FOR
			SELECT DISTINCT * FROM PROBLEMAS,COMENTARIOS 
				WHERE ID_PROBLEMA= xTest;
		RETURN CO_CON5;
	END;
	
	

	
END PC_COMENTARIOS;


                   
