CREATE OR REPLACE PACKAGE PC_EQUIPO IS
	PROCEDURE AD_EQUIPO (xNOMBRE IN VARCHAR,xLUGAR IN NUMBER);
	PROCEDURE MOD_EQUIPO (xID_EQUIPO IN NUMBER);
	
	PROCEDURE AD_PERTENECE_EQU (xID_USUARIO IN VARCHAR,xID_EQUIPO IN NUMBER);
	
	FUNCTION CONS_EQUI RETURN SYS_REFCURSOR;
	FUNCTION CON_PERTENECE RETURN SYS_REFCURSOR;
	FUNCTION CO_EQUI (xNOMBRE IN VARCHAR) RETURN SYS_REFCURSOR;
END PC_EQUIPO;


CREATE OR REPLACE PACKAGE BODY PC_EQUIPO IS
	
	PROCEDURE AD_EQUIPO (xNOMBRE IN VARCHAR,xLUGAR IN NUMBER) IS
		BEGIN
		INSERT INTO EQUIPOS (ID_EQUIPO,NOMBRE,LUGAR) VALUES (SEQ_EQUIPOS.NEXTVAL,xNOMBRE,xLUGAR);
		COMMIT;
		EXCEPTION
		WHEN OTHERS THEN
		ROLLBACK;
		RAISE_APPLICATION_ERROR(-20032,'No se puede insertar en equipo.');
	END;
	
	PROCEDURE MOD_EQUIPO (xID_EQUIPO IN NUMBER) IS
		BEGIN
		UPDATE EQUIPOS SET FECHA_FIN= SYSDATE WHERE ID_EQUIPO= xID_EQUIPO;
		COMMIT;
		EXCEPTION
		WHEN OTHERS THEN
		ROLLBACK;
		RAISE_APPLICATION_ERROR (-20021,'No se puede modificar el equipo.');
	END;
	
	PROCEDURE AD_PERTENECE_EQU (xID_USUARIO IN VARCHAR,xID_EQUIPO IN NUMBER) IS
		BEGIN
		INSERT INTO PERTENECE_EQUIPO (ID_USUARIO,ID_EQUIPO) VALUES (xID_USUARIO,xID_EQUIPO) ;
		COMMIT;
		EXCEPTION
		WHEN OTHERS THEN
		ROLLBACK;
		RAISE_APPLICATION_ERROR(-20033,'No se puede insertar en pertenece a equipo.');
	END;
	
	FUNCTION CO_EQUI (xNOMBRE IN VARCHAR) RETURN SYS_REFCURSOR IS CON_EQUI SYS_REFCURSOR;
		BEGIN
		OPEN CON_EQUI FOR
			SELECT * FROM USUARIOS,(SELECT * FROM PERTENECE_EQUIPO
			WHERE ID_EQUIPO= (SELECT ID_EQUIPO FROM PERTENECE_EQUIPO WHERE ID_USUARIO= xNOMBRE AND ROWNUM <= 1)) 
			WHERE USERNAME= ID_USUARIO;	
		RETURN CON_EQUI;
	END;
	
	
	FUNCTION CONS_EQUI RETURN SYS_REFCURSOR IS CON_EQUI SYS_REFCURSOR;
		BEGIN
		OPEN CON_EQUI FOR
			SELECT * FROM EQUIPOS;
		RETURN CON_EQUI;
	END;
	
	FUNCTION CON_PERTENECE RETURN SYS_REFCURSOR IS CO_PERTENECE SYS_REFCURSOR;
		BEGIN
		OPEN CO_PERTENECE FOR
			SELECT * FROM PERTENECE_EQUIPO;
		RETURN CO_PERTENECE;
	END;
	
END PC_EQUIPO;