CREATE OR REPLACE PACKAGE PC_RGRUPO IS
	/*GRUPO*/
	PROCEDURE AD_GRUPO (xNOMBRE IN VARCHAR, xCREADOR IN VARCHAR);
	
	/*TIENE*/
	PROCEDURE AD_TIENE (xID_GRUPO IN NUMBER, xID_TEMA IN VARCHAR);
	
	/*PERTENECE GRUPO*/
	PROCEDURE AD_PERTENECE (xID_USUARIO IN VARCHAR, xID_GRUPO IN NUMBER);
	
	FUNCTION CO_GRUPO RETURN SYS_REFCURSOR;
	FUNCTION CONS_GRUPO RETURN SYS_REFCURSOR;
	FUNCTION CO_TIENE RETURN SYS_REFCURSOR;
	FUNCTION CO_PERTENECE RETURN SYS_REFCURSOR;

END PC_RGRUPO;

CREATE OR REPLACE PACKAGE BODY PC_RGRUPO IS

	PROCEDURE AD_GRUPO (xNOMBRE IN VARCHAR, xCREADOR IN VARCHAR) IS
		BEGIN
		INSERT INTO GRUPOS (ID_GRUPO,NOMBRE,CREADOR) VALUES (SEQ_GRUPOS.NEXTVAL,xNOMBRE,xCREADOR);
		COMMIT;
		EXCEPTION
		WHEN OTHERS THEN
		ROLLBACK;
		RAISE_APPLICATION_ERROR(-20032,'No se puede insertar en grupos.');
	END;

	
	PROCEDURE AD_TIENE (xID_GRUPO IN NUMBER, xID_TEMA IN VARCHAR) IS
		BEGIN
		INSERT INTO GRUPO_TIENE_TEMA (ID_GRUPO,ID_TEMA) VALUES (xID_GRUPO,xID_TEMA);
		COMMIT;
		EXCEPTION
		WHEN OTHERS THEN
		ROLLBACK;
		RAISE_APPLICATION_ERROR(-20033,'No se puede insertar en grupo tiene tema.');
	END;
	

	PROCEDURE AD_PERTENECE (xID_USUARIO IN VARCHAR, xID_GRUPO IN NUMBER) IS 
		BEGIN 
		INSERT INTO PERTENECE_GRUPO (ID_USUARIO,ID_GRUPO) VALUES (xID_USUARIO,xID_GRUPO);
		COMMIT;
		EXCEPTION
		WHEN OTHERS THEN
		ROLLBACK;
		RAISE_APPLICATION_ERROR(-20033,'No se puede insertar en pertenece grupo.');
	END;
	

	FUNCTION CO_GRUPO RETURN SYS_REFCURSOR IS CON_GRUPO SYS_REFCURSOR;
		BEGIN
		OPEN CON_GRUPO FOR
			SELECT DISTINCT USERNAME,U.NOMBRE,ID_GRUPO,G.NOMBRE  FROM USUARIOS U,GRUPOS  G
			WHERE G.CREADOR= USERNAME;
		RETURN CON_GRUPO;
	END;
	
	FUNCTION CONS_GRUPO RETURN SYS_REFCURSOR IS CO_GRUP SYS_REFCURSOR;
		BEGIN 
		OPEN CO_GRUP FOR
			SELECT * FROM GRUPOS;
		RETURN CO_GRUP;
	END;
	
	FUNCTION CO_TIENE RETURN SYS_REFCURSOR IS CON_TIENE SYS_REFCURSOR;
		BEGIN
		OPEN CON_TIENE FOR
			SELECT * FROM GRUPO_TIENE_TEMA;
		RETURN CON_TIENE;
	END;
	
	FUNCTION CO_PERTENECE RETURN SYS_REFCURSOR IS CON_PERTENECE SYS_REFCURSOR;
		BEGIN
		OPEN CON_PERTENECE FOR
			SELECT * FROM PERTENECE_GRUPO;
		RETURN CON_PERTENECE;
	END;
	
END PC_RGRUPO;



