CREATE OR REPLACE PACKAGE PC_COMENTARIOS IS 
  /*COMENTARIOS*/
  PROCEDURE AD_COMENTARIOS (xID_COMENTARIO IN NUMBER, xEXPLICACION  IN VARCHAR,xFECHA IN DATE,xGRUPO IN NUMBER,xUSUARIO  IN VARCHAR,xPROBLEMA  IN  NUMBER,xID_COMENTARIO_RESPUESTA IN NUMBER);
  FUNCTION CO_COMENTARIOS  RETURN SYS_REFCURSOR;
  
  FUNCTION CO_CO4(xTest IN VARCHAR) RETURN SYS_REFCURSOR;
  FUNCTION CO_CO5(xTest IN NUMBER) RETURN SYS_REFCURSOR;

END PC_COMENTARIOS;
/

CREATE OR REPLACE PACKAGE PC_EQUIPO IS
	PROCEDURE AD_EQUIPO (xNOMBRE IN VARCHAR,xLUGAR IN NUMBER);
	PROCEDURE MOD_EQUIPO (xID_EQUIPO IN NUMBER);
	
	PROCEDURE AD_PERTENECE_EQU (xID_USUARIO IN VARCHAR,xID_EQUIPO IN NUMBER);
	
	FUNCTION CONS_EQUI RETURN SYS_REFCURSOR;
	FUNCTION CON_PERTENECE RETURN SYS_REFCURSOR;
	FUNCTION CO_EQUI (xNOMBRE IN VARCHAR) RETURN SYS_REFCURSOR;
END PC_EQUIPO;
/

CREATE OR REPLACE PACKAGE PC_GRUPO IS
	/*GRUPO*/
	PROCEDURE AD_GRUPO (xNOMBRE IN VARCHAR, xCREADOR IN VARCHAR);
	PROCEDURE MOD_GRUPO (xID_GRUPO IN NUMBER, xNOMBRE IN VARCHAR);
	
	/*TIENE*/
	PROCEDURE AD_TIENE (xID_GRUPO IN NUMBER, xID_TEMA IN VARCHAR);
	
	/*PERTENECE GRUPO*/
	PROCEDURE AD_PERTENECE (xID_USUARIO IN VARCHAR, xID_GRUPO IN NUMBER);
	PROCEDURE EL_PERTENECE (xID_USUARIO IN VARCHAR, xID_GRUPO IN NUMBER);
	
	FUNCTION CO_GRUPO RETURN SYS_REFCURSOR;
	FUNCTION CONS_GRUPO RETURN SYS_REFCURSOR;
	FUNCTION CO_TIENE RETURN SYS_REFCURSOR;
	FUNCTION CO_PERTENECE RETURN SYS_REFCURSOR;

END PC_GRUPO;
/

CREATE OR REPLACE PACKAGE PC_PROBLEMA IS 
  /*PRUEBA*/
  PROCEDURE AD_PRUEBA (xID_PRUEBA  IN NUMBER, xINPUT_CASE  IN VARCHAR, xOUTPUT_CASE  IN VARCHAR,xPROPOSITO  IN VARCHAR,xID_PROBLEMA IN NUMBER);
  PROCEDURE MOD_PRUEBA (xID_PRUEBA  IN NUMBER, xINPUT_CASE  IN VARCHAR, xOUTPUT_CASE  IN VARCHAR,xPROPOSITO  IN VARCHAR,xID_PROBLEMA IN NUMBER);
  PROCEDURE ELI_PRUEBA (xID_PRUEBA  IN NUMBER);
  FUNCTION CO_PRUEBA  RETURN SYS_REFCURSOR;
   
  /*PROBLEMA*/  
  PROCEDURE AD_PROBLEMA  (xID_PROBLEMA  IN NUMBER,xNOMBRE  IN VARCHAR,xPDF IN  VARCHAR,xTIEMPO IN NUMBER,xMEMORIA  IN VARCHAR,xCREADOR IN VARCHAR,xTEMA  IN VARCHAR);
  PROCEDURE MOD_PROBLEMA (xID_PROBLEMA  IN NUMBER,xTIEMPO IN NUMBER,xMEMORIA  IN VARCHAR,xTEMA  IN VARCHAR);
  PROCEDURE ELI_PROBLEMA (xID_PROBLEMA  IN NUMBER);
  FUNCTION CO_PROBLEMA  RETURN SYS_REFCURSOR;
  FUNCTION CO_CO2 RETURN SYS_REFCURSOR;

END PC_PROBLEMA;
/

CREATE OR REPLACE PACKAGE PC_TEMA IS
	PROCEDURE AD_TEMA (xID_TEMA IN VARCHAR, xNOMBRE IN VARCHAR, xPADRE IN VARCHAR);
	FUNCTION CO_TEMA RETURN SYS_REFCURSOR;
END PC_TEMA;
/

CREATE OR REPLACE PACKAGE PC_USUARIO IS 
/*USUARIO*/
  PROCEDURE AD_USUARIO (xUSERNAME IN  VARCHAR,xNOMBRE IN  VARCHAR,xCORREO IN  VARCHAR,xFECHA  IN DATE,xTELEFONO IN  NUMBER,xOCUPACION IN  VARCHAR,xESTADO  IN VARCHAR,xLUGAR IN NUMBER,xPerfil IN XMLTYPE);
  PROCEDURE MOD_USUARIO (xUSERNAME IN  VARCHAR,xNOMBRE IN  VARCHAR,xCORREO IN  VARCHAR,xTELEFONO IN  NUMBER,xOCUPACION IN  VARCHAR,xESTADO  IN VARCHAR,xLUGAR IN NUMBER,xPerfil IN XMLTYPE);
  PROCEDURE ELI_USUARIO (xUSERNAME IN  VARCHAR);
  FUNCTION CO_USUARIOS  RETURN SYS_REFCURSOR;
  /*Consultas*/
  FUNCTION CO_CO6 RETURN SYS_REFCURSOR;
  FUNCTION CO_CO7 RETURN SYS_REFCURSOR;
END PC_USUARIO;
/

CREATE OR REPLACE PACKAGE PC_RGRUPO IS
	/*GRUPO*/
	PROCEDURE AD_GRUPO (xNOMBRE IN VARCHAR, xCREADOR IN VARCHAR);
	
	/*TIENE*/
	PROCEDURE AD_TIENE (xID_GRUPO IN NUMBER, xID_TEMA IN VARCHAR);
	
	/*PERTENECE GRUPO*/
	PROCEDURE AD_PERTENECE (xID_USUARIO IN VARCHAR, xID_GRUPO IN NUMBER);
	
	FUNCTION CO_GRUPO RETURN SYS_REFCURSOR;
	FUNCTION CONS_GRUPO RETURN SYS_REFCURSOR;
	FUNCTION CO_TIENE RETURN SYS_REFCURSOR;
	FUNCTION CO_PERTENECE RETURN SYS_REFCURSOR;

END PC_RGRUPO;
