--CONSULTAR VIDEOS CON ERRORES

select tema.nombre as Tema, temporal.url as URL,COUNT(opinion.numero) as Numero_Opiniones_ERROR
from tema,contenidoTema,Temporal,Opinion
where tema.nombre =contenidoTema.tema and  contenidoTema.contenido = temporal.nombre and
temporal.nombre = opinion.contenidoid 
GROUP BY TEMA.NOMBRE,TEMPORAL.URL,OPINION.NUMERO
ORDER BY OPINION.NUMERO;  

--CONSULTAR LOS DIEZ MAS POPULARES DEL MES
SELECT PERFIL.NOMBRE AS PERFIL, TEMPORAL.NOMBRE ,TEMPORAL.URL, COUNT(CONSULTA.CONTENIDO) AS VECES
FROM  CONSULTA,TEMPORAL,PERFIL
WHERE CONSULTA.PERFIL =  PERFIL.CORREO AND CONSULTA.CONTENIDO = TEMPORAL.NOMBRE
GROUP BY PERFIL.NOMBRE,TEMPORAL.NOMBRE,TEMPORAL.URL,CONSULTA.CONTENIDO
ORDER BY COUNT(CONTENIDO);
--CONSULTAR LOS CONTENIDOS SIN FILTROS FALTA
select TEMPORAL.NOMBRE AS NOMBRE,TEMPORAL.FECHA AS FECHA,TEMPORAL.URL AS  URL,TEMPORAL.TIPO,
TEMPORAL.PERFIL AS PERFIL ,TEMPORAL.DURACION AS DURACION,TEMPORAL.IDIOMA AS IDIOMA
FROM TEMPORAL FULL JOIN CONTENIDOFILTRO
ON TEMPORAL.NOMBRE = CONTENIDOFILTRO.CONTENIDO;

--CONSULTAR LOS CONTENIDOIS DE UN TEMA
SELECT TEMPORAL.NOMBRE AS TITULO, COUNT(OPINION.NUMERO) AS OPINIONES
FROM TEMPORAL,OPINION
WHERE OPINION.CONTENIDOID = TEMPORAL.NOMBRE 
GROUP BY TEMPORAL.NOMBRE,OPINION.NUMERO
ORDER BY OPINION.NUMERO;

--CONSULTAR LOS TEMAS QUE NO TIENEN UN CONTENIDO
SELECT TEMA.NOMBRE AS TEMA ,TEMA.PERFIL AS PERFIL
FROM TEMA 
WHERE TEMA.NOMBRE NOT IN (SELECT TEMA FROM CONTENIDOTEMA); 
