ALTER TABLE Consulta ADD CONSTRAINT FK_CONSULTA_PERFIL FOREIGN KEY (perfil) 
REFERENCES Perfil(correo);

ALTER TABLE Consulta ADD CONSTRAINT FK_CONSULTA_TEMPORAL FOREIGN KEY (contenido)
REFERENCES Temporal(nombre);

ALTER TABLE Opinion  ADD CONSTRAINT FK_OPINION_PERFIL FOREIGN KEY (perfilc)
REFERENCES Perfil(correo);
ALTER TABLE Opinion  ADD CONSTRAINT FK_OPINION_TEMPORAL FOREIGN KEY (contenidoid)
REFERENCES Temporal(nombre);

ALTER TABLE Adjetivo ADD CONSTRAINT FK_ADJETIVO_OPINION FOREIGN KEY (opinion)
REFERENCES Opinion(numero);

ALTER TABLE Temporal ADD CONSTRAINT FK_TEMPORAL_PERFIL FOREIGN KEY (perfil)
REFERENCES Perfil(correo);

ALTER TABLE Etiqueta ADD CONSTRAINT FK_ETIQUETA_TEMPORAL FOREIGN KEY (temporal)
REFERENCES Temporal(nombre);

ALTER TABLE Tema ADD CONSTRAINT FK_TEMA_PERFIL FOREIGN KEY (perfil)
REFERENCES Perfil(correo);

ALTER TABLE Palabra ADD CONSTRAINT FK_PALABRA_TEMA FOREIGN KEY (tema)
REFERENCES Tema(nombre);

ALTER TABLE EsPrerrequisito ADD CONSTRAINT FK_ESPRERREQUISITOA_TEMA FOREIGN KEY (nombreTemaA)
REFERENCES Tema(nombre);
ALTER TABLE EsPrerrequisito ADD CONSTRAINT FK_ESPRERREQUISITOB_TEMA FOREIGN KEY (nombreTemaB)
REFERENCES Tema(nombre);

ALTER TABLE EsSubtema ADD CONSTRAINT  FK_ESSUBTEMAA_TEMA FOREIGN KEY (nombreTemaA)
REFERENCES Tema(nombre);
ALTER TABLE EsSubtema ADD CONSTRAINT  FK_ESSUBTEMAB_TEMA FOREIGN KEY (nombreTemaB)
REFERENCES Tema(nombre);

ALTER TABLE Trata ADD CONSTRAINT FK_TRATA_TEMA FOREIGN KEY (tema) 
REFERENCES Tema(nombre);
ALTER TABLE Trata ADD CONSTRAINT FK_TRATA_ASIGNATURA FOREIGN KEY (asignatura)
REFERENCES Asignatura(sigla);

ALTER TABLE ContenidoFiltro ADD CONSTRAINT FK_CONTENIDOFILTRO_TEMPORAL FOREIGN KEY (contenido)
REFERENCES Temporal(nombre);
ALTER TABLE ContenidoFiltro  ADD CONSTRAINT FK_CONTENIDOFILTRO_FILTRO FOREIGN KEY (filtro)
REFERENCES Filtro(nombre);

ALTER TABLE ContenidoTema ADD CONSTRAINT FK_ContenidoTema_Contenido FOREIGN KEY (contenido)
REFERENCES Temporal(nombre);
ALTER TABLE ContenidoTema ADD CONSTRAINT FK_ContenidoTema_Tema FOREIGN KEY (tema)
REFERENCES Tema(nombre);