--seguridad b
GRANT EXECUTE ON PA_AUDITOR TO bd2154346;
--seguridad c
CREATE ROLE ADMINISTRADOR;
CREATE ROLE PERFILESS;
GRANT PERFILES TO bd2154346;
GRANT PERFILES TO bd2152008;
GRANT EXECUTE ON PA_PERFIL TO PERFILESS;

--seguridad D 

REVOKE EXECUTE ON PA_AUDITOR FROM bd2154346;
DROP ROLE PERFILESS;
DROP ROLE ADMINISTRADOR;

--seguridad ok
--seguridad No_ok


