ALTER TABLE Consulta DROP CONSTRAINT FK_CONSULTA_PERFIL;
ALTER TABLE Consulta DROP CONSTRAINT FK_CONSULTA_TEMPORAL;

ALTER TABLE Opinion  DROP CONSTRAINT FK_OPINION_PERFIL;
ALTER TABLE Opinion DROP CONSTRAINT FK_OPINION_TEMPORAL;

ALTER TABLE Adjetivo DROP CONSTRAINT FK_ADJETIVO_OPINION;

ALTER TABLE Temporal DROP CONSTRAINT FK_TEMPORAL_PERFIL;

ALTER TABLE Etiqueta DROP CONSTRAINT FK_ETIQUETA_TEMPORAL;

ALTER TABLE Tema DROP CONSTRAINT FK_TEMA_PERFIL;

ALTER TABLE Palabra DROP CONSTRAINT FK_PALABRA_TEMA;

ALTER TABLE EsPrerrequisito DROP CONSTRAINT FK_ESPRERREQUISITOA_TEMA;
ALTER TABLE EsPrerrequisito DROP CONSTRAINT FK_ESPRERREQUISITOB_TEMA;

ALTER TABLE EsSubtema DROP CONSTRAINT  FK_ESSUBTEMAA_TEMA;
ALTER TABLE EsSubtema DROP CONSTRAINT  FK_ESSUBTEMAB_TEMA;

ALTER TABLE Trata DROP CONSTRAINT FK_TRATA_TEMA;
ALTER TABLE Trata DROP CONSTRAINT FK_TRATA_ASIGNATURA;

ALTER TABLE ContenidoFiltro DROP CONSTRAINT FK_CONTENIDOFILTRO_TEMPORAL;
ALTER TABLE ContenidoFiltro  DROP CONSTRAINT FK_CONTENIDOFILTRO_FILTRO;

ALTER TABLE ContenidoTema DROP CONSTRAINT FK_CONTENIDOTEMA_CONTENIDO;
ALTER TABLE ContenidoTema DROP CONSTRAINT FK_CONTENIDOTEMA_TEMA;