ALTER TABLE Perfil DROP CONSTRAINT PK_PERFIL;
ALTER TABLE Temporal DROP CONSTRAINT PK_TEMPORAL;
ALTER TABLE Opinion DROP CONSTRAINT PK_OPINION;
ALTER TABLE Tema DROP CONSTRAINT PK_TEMA;
ALTER TABLE Asignatura  DROP CONSTRAINT PK_ASIGNATURA;
ALTER TABLE Filtro DROP CONSTRAINT PK_FILTRO;
ALTER TABLE ContenidoTema DROP CONSTRAINT PK_CONTENIDO_TEMA; 
ALTER TABLE Consulta DROP CONSTRAINT PK_PERFIL_CONTENIDO;