DELETE FROM ofrecidoPor;
DELETE FROM contiene;
DELETE FROM promocion;
DELETE FROM deseaAdquirir;
DELETE FROM sucursal;
DELETE FROM donacion;
DELETE FROM cadena;
DELETE FROM producto;
DELETE FROM cliente;