CREATE OR REPLACE PACKAGE PA_Administrador IS
    FUNCTION CO_Premiados RETURN XMLTYPE;
    FUNCTION CO_Composiciones RETURN SYS_REFCURSOR;
END PA_Administrador;

CREATE OR REPLACE PACKAGE PA_Musico IS
    FUNCTION CO_Musicos_Ciudad RETURN SYS_REFCURSOR;
    FUNCTION CO_Musicos_Universidad RETURN XMLTYPE;
    FUNCTION CO_Premiados RETURN XMLTYPE;
END PA_Musico;