
CREATE OR REPLACE PACKAGE PA_ADMINISTRADOR IS
  FUNCTION CO_INTERPRETES RETURN SYS_REFCURSOR;
  FUNCTION CO_INFOMUSICO RETURN XMLTYPE;
END PA_ADMINISTRADOR;

CREATE OR REPLACE PACKAGE PA_CLIENTE IS
  FUNCTION CO_INFORMACION RETURN XMLTYPE;
  FUNCTION CO_HOTELES RETURN SYS_REFCURSOR;  
END PA_CLIENTE;