CREATE OR REPLACE PACKAGE BODY PA_ADMINISTRADOR IS
  FUNCTION CO_INFOMUSICO RETURN XMLTYPE IS CO_MUSICO_XML XMLTYPE;
  BEGIN 
    CO_MUSICO_XML := PC_MUSICO.CO_MUSICO;
    RETURN CO_MUSICO_XML;
  END;
  
  FUNCTION CO_INTERPRETES RETURN SYS_REFCURSOR IS INTERPRETE SYS_REFCURSOR;
  BEGIN
	INTERPRETE := PC_MUSICO.CO_INTERPRETES;
	RETURN INTERPRETE;
  END;
END PA_ADMINISTRADOR;

CREATE OR REPLACE PACKAGE BODY PA_CLIENTE IS
  FUNCTION CO_INFORMACION RETURN XMLTYPE IS CO_MUSICO_XML XMLTYPE;
  BEGIN
    CO_MUSICO_XML :=  PC_MUSICO.CO_MUSICO;
    RETURN CO_MUSICO_XML;
  END;
  
  FUNCTION CO_HOTELES RETURN SYS_REFCURSOR IS HOTELES SYS_REFCURSOR;
  BEGIN
	HOTELES:= PC_LUGAR.CO_HOTELES;
    RETURN HOTELES;
  END;
END PA_CLIENTE;