CREATE OR REPLACE PACKAGE PC_MUSICO IS
  PROCEDURE AD_MUSICO(xm_name IN VARCHAR, xborn  IN DATE, xdied IN DATE, xborn_in IN VARCHAR, xliving_in IN VARCHAR);
  PROCEDURE EL_MUSICO(xm_no IN NUMBER);
  PROCEDURE MOD_MUSICO(xm_no IN NUMBER, xdied IN DATE, xliving_in IN VARCHAR);
  FUNCTION CO_MUSICO RETURN XMLTYPE;
  FUNCTION CO_INTERPRETES RETURN SYS_REFCURSOR;
END PC_MUSICO;

CREATE OR REPLACE PACKAGE PC_LUGAR IS
  PROCEDURE AD_LUGAR(xplace_town IN VARCHAR, xplace_country  IN VARCHAR, xdetalle IN XMLTYPE);
  PROCEDURE MOD_LUGAR(xplace_no IN NUMBER, xdetalle IN XMLTYPE);
  FUNCTION CO_LUGAR RETURN XMLTYPE;
  FUNCTION CO_HOTELES RETURN SYS_REFCURSOR;  
END PC_LUGAR;