CREATE VIEW HARD11 AS 
    SELECT DISTINCT M_NAME,PLACE_TOWN FROM PLACE,PERFORMER,MUSICIAN 
        WHERE M_NO= PERF_IS AND PLACE_NO= BORN_IN AND M_NAME<> 'James First' AND BORN_IN= (SELECT BORN_IN FROM MUSICIAN WHERE M_NAME= 'James First');