ALTER TABLE GUEST ADD CONSTRAINT CK_GUEST_FNAME CHECK (not(REGEXP_LIKE(FIRST_NAME,'^[0-9]{1,1000}+$')));

ALTER TABLE GUEST ADD CONSTRAINT CK_GUEST_LNAME CHECK (not(REGEXP_LIKE(LAST_NAME,'^[0-9]{1,1000}+$')));

ALTER TABLE BOOKING ADD CONSTRAINT CK_BOOKING_ROOM_TYPE_REQUESTED CHECK ((REGEXP_LIKE(OCCUPANTS,'^[[:digit:]]{9}$')) AND 
(ROOM_TYPE_REQUESTED LIKE 'single' OR ROOM_TYPE_REQUESTED LIKE 'twin' OR ROOM_TYPE_REQUESTED LIKE 'family' OR 
ROOM_TYPE_REQUESTED LIKE 'double'));

ALTER TABLE BOOKING DROP CONSTRAINT CK_BOOKING_ROOM_TYPE_REQUESTED;
