ALTER TABLE EQUIPOS ADD CONSTRAINT PK_EQUIPOS
 PRIMARY KEY(ID_EQUIPO);

ALTER TABLE LUGARES ADD CONSTRAINT PK_LUEGARES
 PRIMARY KEY(ID_LUGAR);

ALTER TABLE PROBLEMAS ADD CONSTRAINT PK_PROBLEMAS
 PRIMARY KEY(ID_PROBLEMA);

ALTER TABLE PERTENECE_EQUIPO ADD CONSTRAINT PK_PERTENECE_EQUIPO
 PRIMARY KEY(ID_USUARIO,ID_EQUIPO);

ALTER TABLE GRUPO_TIENE_TEMA ADD CONSTRAINT PK_GRUPO_TIENE_TEMA
 PRIMARY KEY(ID_GRUPO,ID_TEMA);

ALTER TABLE COMENTARIOS ADD CONSTRAINT PK_COMENTARIOS 
 PRIMARY KEY(ID_COMENTARIO);

ALTER TABLE TEMAS ADD CONSTRAINT PK_TEMAS 
 PRIMARY KEY(ID_TEMA);

ALTER TABLE PRUEBAS ADD CONSTRAINT PK_PRUEBAS
 PRIMARY KEY(ID_PRUEBA);

ALTER TABLE GRUPOS ADD CONSTRAINT PK_GRUPOS
 PRIMARY KEY(ID_GRUPO);

ALTER TABLE PERTENECE_GRUPO ADD CONSTRAINT PK_PERTENECE_GRUPO
 PRIMARY KEY(ID_USUARIO,ID_GRUPO);
 
ALTER TABLE USUARIOS ADD CONSTRAINT PK_USUARIOS
 PRIMARY KEY(UserName);