--CONSULTAR VIDEOS CON ERRORES

select TEMA.NOMBRE AS TEMA ,TEMPORAL.URL AS URL, COUNT(OPINION.NUMERO) AS numeroOpiniones, COUNT(OPINION.NUMERO)
from TEMA ,TEMPORAL,CONTENIDOTEMA,OPINION
WHERE TEMA.NOMBRE = CONTENIDOTEMA.TEMA AND  TEMPORAL.NOMBRE = CONTENIDOTEMA.CONTENIDO AND TEMPORAL.NOMBRE = OPINION.CONTENIDOID AND OPINION.DETALLE = 'momentos de error' AND  TEMPORAL.TIPO ='V'
GROUP BY TEMA.NOMBRE, TEMPORAL.URL,OPINION.NUMERO;

--consultar los diez mas populares del mes 

select temporal.perfil as Perfil, temporal.nombre  as Titulo, temporal.url as URL
from temporal,consulta
where temporal.nombre = consulta.contenido and SUBSTR(TO_CHAR(consulta.fecha,'YYYY-MM-DD'),6,2) =SUBSTR(TO_CHAR(SYSDATE,'YYYY-MM-DD'),6,2)
ORDER BY TEMPORAL.NOMBRE;

--CONSULTAR LOS CONTENIDOS DE UN TEMA 
SELECT tema.nombre as Titulo ,count(opinion.tipo) as Numero_Opiniones
from TEMA ,TEMPORAL,CONTENIDOTEMA,OPINION
WHERE TEMA.NOMBRE = CONTENIDOTEMA.TEMA AND  TEMPORAL.NOMBRE = CONTENIDOTEMA.CONTENIDO AND TEMPORAL.NOMBRE = OPINION.CONTENIDOID AND opinion.tipo in ('E','G')
group by TEMA
order by count(opinion.tipo);


--CONSULTAR LOS CONTENIDOS SIN FILTROS

SELECT * 
FROM  TEMPORAL LEFT JOIN CONTENIDOFILTRO ON (TEMPORAL.NOMBRE = CONTENIDOFILTRO.CONTENIDO)
WHERE CONTENIDOFILTRO.CONTENIDO IS NULL;

-- CONSULTAR LOS TEMAS QUE NO TIENEN CONTENIDO

SELECT * 
FROM TEMA LEFT JOIN  CONTENIDOTEMA ON (TEMA.NOMBRE = CONTENIDOTEMA.TEMA)
WHERE CONTENIDOTEMA.CONTENIDO IS NULL;
