/*SEGURIDAD OK*/
EXECUTE PA_USUARIO.AD_COMEN (300,'Requiero ayuda en el problema 853',TO_DATE('2007/07/09', 'yyyy/mm/dd'),1,'srd98',853,null);

SELECT PA_USUARIO.CO_COMEN FROM DUAL;

SELECT PA_USUARIO.CO_COMEN FROM DUAL;

SELECT PA_USUARIO.CO_PRU FROM DUAL;

SELECT PA_USUARIO.CO_PRO FROM DUAL;

SELECT PA_USUARIO.CO_EQUI FROM DUAL;

SELECT PA_USUARIO.CO_PRO_CO2 FROM DUAL;

SELECT PA_USUARIO.CO_GRUPO FROM DUAL;

SELECT PA_USUARIO.CO_COM_CO4('CrkJohn') FROM DUAL;

SELECT PA_USUARIO.CO_COM_CO4(919) FROM DUAL;


