CREATE ROLE USUARIO;
DROP ROLE USUARIO;
CREATE ROLE ASOCIACION;
DROP ROLE ASOCIACION;

GRANT EXECUTE ON PA_USUARIO TO USUARIO;

REVOKE EXECUTE ON PA_USUARIO FROM USUARIO;

GRANT EXECUTE ON PA_ASOCIACION TO ASOCIACION;

REVOKE EXECUTE ON PA_ASOCIACION FROM ASOCIACION;

