CREATE OR REPLACE PACKAGE PA_ADMIN IS
	PROCEDURE AD_Asociacion (xnombre IN VARCHAR , xacreditacion IN NUMBER, xproposito IN VARCHAR,xlugar IN NUMBER);
	PROCEDURE MOD_Asociacion (xID_Asociacion IN NUMBER,xacreditacion IN NUMBER,xlugar IN NUMBER);
	PROCEDURE EL_Asociacion (xID_Asociacion IN NUMBER);
	
	PROCEDURE AD_REALIZAN (xid_evento IN NUMBER, xid_asociacion IN NUMBER);
	FUNCTION MAYOR_INGRESO RETURN SYS_REFCURSOR;
END PA_ADMIN;

/
CREATE OR REPLACE PACKAGE PA_ASOCIACION IS 
	/*CICLO 1*/
	PROCEDURE AD_ASOCIACION_USUARIO (xUSERNAME IN  VARCHAR,xNOMBRE IN  VARCHAR,xCORREO IN  VARCHAR,xFECHA  IN DATE,xTELEFONO IN  NUMBER,xOCUPACION IN  VARCHAR,xESTADO  IN VARCHAR,xLUGAR IN NUMBER,xPerfil IN XMLTYPE);
	PROCEDURE MOD_ASOCIACION_USUARIO (xUSERNAME IN  VARCHAR,xNOMBRE IN  VARCHAR,xCORREO IN  VARCHAR,xTELEFONO IN  NUMBER,xOCUPACION IN  VARCHAR,xESTADO  IN VARCHAR,xLUGAR IN NUMBER,xPerfil IN XMLTYPE);
	PROCEDURE ELI_ASOCIACION_USUARIO (xUSERNAME IN  VARCHAR);
	FUNCTION CO_ASOCIACION_USUARIOS  RETURN SYS_REFCURSOR;
	PROCEDURE AD_ASOCIACION_PROBLEMA  (xID_PROBLEMA  IN NUMBER,xNOMBRE  IN VARCHAR,xPDF IN  VARCHAR,xTIEMPO IN NUMBER,xMEMORIA  IN VARCHAR,xCREADOR IN VARCHAR,xTEMA  IN VARCHAR);
	PROCEDURE MOD_ASOCIACION_PROBLEMA (xID_PROBLEMA  IN NUMBER,xTIEMPO IN NUMBER,xMEMORIA  IN VARCHAR,xTEMA  IN VARCHAR);
	PROCEDURE ELI_ASOCIACION_PROBLEMA (xID_PROBLEMA  IN NUMBER);
	FUNCTION CO_ASOCIACION_PROBLEMA  RETURN SYS_REFCURSOR;
	PROCEDURE AD_ASOCIACION_PRUEBA (xID_PRUEBA  IN NUMBER, xINPUT_CASE  IN VARCHAR, xOUTPUT_CASE  IN VARCHAR,xPROPOSITO  IN VARCHAR,xID_PROBLEMA IN NUMBER);
	PROCEDURE MOD_ASOCIACION_PRUEBA (xID_PRUEBA  IN NUMBER, xINPUT_CASE  IN VARCHAR, xOUTPUT_CASE  IN VARCHAR,xPROPOSITO  IN VARCHAR,xID_PROBLEMA IN NUMBER);
	PROCEDURE ELI_ASOCIACION_PRUEBA (xID_PRUEBA  IN NUMBER);
	FUNCTION CO_ASOCIACION_PRUEBA  RETURN SYS_REFCURSOR;
	PROCEDURE AD_ASOCIACION_GRUPO (xNOMBRE IN VARCHAR, xCREADOR IN VARCHAR);
	PROCEDURE MOD_ASOCIACION_GRUPO (xID_GRUPO IN NUMBER, xNOMBRE IN VARCHAR);
	PROCEDURE AD_ASOCIACION_TIENE (xID_GRUPO IN NUMBER, xID_TEMA IN VARCHAR);
	PROCEDURE AD_ASOCIACION_PERTENECE (xID_USUARIO IN VARCHAR, xID_GRUPO IN NUMBER);
	PROCEDURE EL_ASOCIACION_PERTENECE (xID_USUARIO IN VARCHAR, xID_GRUPO IN NUMBER);
	FUNCTION CO_ASOCIACION_GRUPO RETURN SYS_REFCURSOR;	
	FUNCTION CONS_ASOCIOACION_GRUPO RETURN SYS_REFCURSOR;
	FUNCTION CO_ASOCIOACION_TIENE RETURN SYS_REFCURSOR;
	FUNCTION CO_ASOCIOACION_PERTENECE RETURN SYS_REFCURSOR;
	PROCEDURE AD_ASOCIACION_TEMA (xID_TEMA IN VARCHAR, xNOMBRE IN VARCHAR, xPADRE IN VARCHAR);
	FUNCTION CO_ASOCIACION_TEMA RETURN SYS_REFCURSOR;
	/*CICLO 2*/
	PROCEDURE AD_EVENTO (xid_evento IN NUMBER,xnombre IN VARCHAR, xnivel IN VARCHAR, xfecha IN DATE, xfechafin IN DATE,xcantidad_equipos IN NUMBER, xclase IN VARCHAR, xcosto IN NUMBER, xlugar IN NUMBER, xcapacidad_maxima IN NUMBER);
	PROCEDURE AD_TIENE (xproblema IN NUMBER, xevento IN NUMBER);

	FUNCTION MEJOR_EQUIPO RETURN SYS_REFCURSOR;
	FUNCTION RESULTADO_SCORE (xid_evento IN NUMBER)  RETURN SYS_REFCURSOR;
	FUNCTION CONFERENCIAS RETURN SYS_REFCURSOR;
	FUNCTION PREPARACION RETURN SYS_REFCURSOR;
	FUNCTION FACT_ECONO RETURN SYS_REFCURSOR;
	FUNCTION PROBLEMAS (xid_evento IN NUMBER) RETURN SYS_REFCURSOR;

END PA_ASOCIACION;
/
CREATE OR REPLACE PACKAGE PA_LIDER_EQUIPO IS
	PROCEDURE AD_INSCRIPCION (xvalor IN NUMBER, xequipo IN NUMBER, xevento IN NUMBER);
	PROCEDURE AD_ENVIOS (xproblema IN NUMBER, xequipo IN NUMBER, xevento IN NUMBER, xlenguage IN VARCHAR);
	PROCEDURE AD_VEREDICTO (xtiempo IN NUMBER, xlenguage IN VARCHAR, xresultado IN VARCHAR, xenvio IN NUMBER, xproblema IN NUMBER, xusuario IN VARCHAR);
	FUNCTION MEJOR_EQUIPO RETURN SYS_REFCURSOR;
	FUNCTION RESULTADO_SCORE (xid_evento IN NUMBER)  RETURN SYS_REFCURSOR;
	FUNCTION CONFERENCIAS RETURN SYS_REFCURSOR;
	FUNCTION PREPARACION RETURN SYS_REFCURSOR;
	FUNCTION FACT_ECONO RETURN SYS_REFCURSOR;
	FUNCTION PROBLEMAS (xid_evento IN NUMBER) RETURN SYS_REFCURSOR;
END PA_LIDER_EQUIPO;

