-----------------------XTablas
--FK DROP
ALTER TABLE casas
DROP CONSTRAINT FK_CASAS_PAISES;

ALTER TABLE tiene_pres
DROP CONSTRAINT FK_TIENE_PRES_PRESC;

ALTER TABLE tiene_pres
DROP CONSTRAINT FK_TIENE_PRES_LIC;

ALTER TABLE licores_especificos
DROP CONSTRAINT FK_LICORES_ESP_CASA;

ALTER TABLE licores_especificos
DROP CONSTRAINT FK_LICORES_ESP_LICOR;

ALTER TABLE licor_anejo
DROP CONSTRAINT FK_LICOR_ANEJO_LIC_ESP;

ALTER TABLE licor
DROP CONSTRAINT FK_LICOR_PAIS;

ALTER TABLE en_base
DROP CONSTRAINT FK_EN_BASE_LICOR;

ALTER TABLE pasos
DROP CONSTRAINT FK_PREPARACION_COCTEL;

ALTER TABLE ingredientes
DROP CONSTRAINT FK_INGREDIENTES_COCTEL;

ALTER TABLE contiene
DROP CONSTRAINT FK_CONTIENE_LICOR;

ALTER TABLE contiene
DROP CONSTRAINT FK_CONTIENE_COCTEL;

ALTER TABLE esde
DROP CONSTRAINT FK_ESDE_FACT_COMP;

ALTER TABLE esde
DROP CONSTRAINT FK_ESDE_LIC_ESP;

--XPOBLAR
DELETE FROM casas;
DELETE FROM coctel;
DELETE FROM contiene;
DELETE FROM en_base;
DELETE FROM esde;
DELETE FROM factura_compra;
DELETE FROM ingredientes;
DELETE FROM licor;
DELETE FROM licor_anejo;
DELETE FROM licores_especificos;
DELETE FROM paises;
DELETE FROM pasos;
DELETE FROM presentaciones;
DELETE FROM tiene_pres;

--XTABLAS
DROP TABLE casas;
DROP TABLE coctel;
DROP TABLE contiene;
DROP TABLE en_base;
DROP TABLE esde;
DROP TABLE factura_compra;
DROP TABLE ingredientes;
DROP TABLE licor;
DROP TABLE licor_anejo;
DROP TABLE licores_especificos;
DROP TABLE paises;
DROP TABLE pasos;
DROP TABLE presentaciones;
DROP TABLE tiene_pres;