REVOKE adm_envios FROM bd2103370;
REVOKE adm_sucursales FROM bd2103370;
REVOKE cliente FROM bd2103370;

REVOKE EXECUTE ON PA_ADMIN_ENVIOS FROM adm_envios;
REVOKE EXECUTE ON PA_ADMIN_SUCURSALES FROM adm_sucursales;
REVOKE EXECUTE ON PA_CLIENTE FROM cliente;

DROP ROLE adm_envios;
DROP ROLE adm_sucursales;
DROP ROLE cliente;

DROP PACKAGE PA_ADMIN_ENVIOS;
DROP PACKAGE PA_ADMIN_SUCURSALES;
DROP PACKAGE PA_CLIENTE;