CREATE OR REPLACE PACKAGE PA_ADMIN_DONACIONES IS
    PROCEDURE AD_DONACION(xdonante IN INTEGER);
    PROCEDURE AD_CONTIENE(xdonacion IN INTEGER, xproducto IN INTEGER, xcantidad IN INTEGER);
END PA_ADMIN_DONACIONES;
/

CREATE OR REPLACE PACKAGE PA_ADMIN_SUCURSALES IS
    PROCEDURE AD_CADENA(xnombre IN VARCHAR);
    PROCEDURE MO_CADENA(xidCadena IN INTEGER, xnombre IN VARCHAR);
    PROCEDURE AD_SUCURSAL(xcadena IN INTEGER, xlocalidad IN VARCHAR, xbarrio IN VARCHAR, xdireccion IN VARCHAR);
    PROCEDURE MO_SUCURSAL(xidSucursal IN INTEGER, xlocalidad IN VARCHAR, xbarrio IN VARCHAR, xdireccion IN VARCHAR);
    PROCEDURE EL_SUCURSAL(xidSucursal IN INTEGER);
END PA_ADMIN_SUCURSALES;
/

CREATE OR REPLACE PACKAGE PA_ORG_PRODUCTOS IS
    PROCEDURE AD_PRODUCTO(xfabricante IN VARCHAR, xnombre IN VARCHAR, xprecio IN NUMBER, xfechaVencimiento IN DATE);
    PROCEDURE MO_PRODUCTO(xidProducto IN INTEGER, xprecio IN NUMBER);
    PROCEDURE EL_PRODUCTO(xidProducto IN INTEGER);
    PROCEDURE AD_PROMOCION(xidProducto  IN  INTEGER, xfInicio IN VARCHAR, xfFinal IN VARCHAR, xdescuento IN NUMBER);
    PROCEDURE MO_PROMOCION(xidPromocion IN INTEGER, xfFinal IN DATE);
END PA_ORG_PRODUCTOS;
/

CREATE OR REPLACE PACKAGE PA_ADMIN_SISTEMA IS
    PROCEDURE AD_CLIENTE(xtipoDocumento IN VARCHAR, xnDocumento IN INTEGER, xnombre IN VARCHAR);
    PROCEDURE MO_CLIENTE(xidCliente  IN  INTEGER, xtipoDocumento IN VARCHAR, xnDocumento IN INTEGER, xnombre IN VARCHAR);
    PROCEDURE EL_CLIENTE(xidCliente IN INTEGER);
    PROCEDURE AD_DESEO(xcliente  IN  INTEGER, xproducto  IN  INTEGER);
    PROCEDURE EL_DESEO(xcliente IN INTEGER, xproducto IN INTEGER);
END PA_ADMIN_SISTEMA;
/

CREATE OR REPLACE PACKAGE PA_CLIENTE IS
    FUNCTION CO_SUCURSALES RETURN SYS_REFCURSOR;
    FUNCTION CO_PROMOCIONES RETURN SYS_REFCURSOR;
    FUNCTION CO_LISTADESEOS(xidCliente IN INTEGER) RETURN SYS_REFCURSOR;
END PA_CLIENTE;
/

CREATE OR REPLACE PACKAGE PA_BANCO_ALIMENTOS IS
    FUNCTION CO_DONANTES RETURN SYS_REFCURSOR;
END PA_BANCO_ALIMENTOS;
/