CREATE OR REPLACE PACKAGE PA_USUARIO IS 
  /*COMENTARIOS*/
  PROCEDURE AD_COMEN (xID_COMENTARIO IN NUMBER, xEXPLICACION  IN VARCHAR,xFECHA IN DATE,xGRUPO IN NUMBER,xUSUARIO  IN VARCHAR,xPROBLEMA  IN  NUMBER,xID_COMENTARIO_RESPUESTA IN NUMBER);
  FUNCTION CO_COMEN  RETURN SYS_REFCURSOR;
  /*problema*/
  PROCEDURE AD_PRU (xID_PRUEBA  IN NUMBER, xINPUT_CASE  IN VARCHAR, xOUTPUT_CASE  IN VARCHAR,xPROPOSITO  IN VARCHAR,xID_PROBLEMA IN NUMBER);
  FUNCTION CO_PRU  RETURN SYS_REFCURSOR;

  /*Grupo*/
  PROCEDURE AD__GRUPO (xNOMBRE IN VARCHAR, xCREADOR IN VARCHAR);
	PROCEDURE AD__TIENE (xID_GRUPO IN NUMBER, xID_TEMA IN VARCHAR);
	PROCEDURE AD__PERTENECE (xID_USUARIO IN VARCHAR, xID_GRUPO IN NUMBER);
	PROCEDURE EL_PERTENECE (xID_USUARIO IN VARCHAR, xID_GRUPO IN NUMBER);
  FUNCTION CO__GRUPO RETURN SYS_REFCURSOR;
	FUNCTION CONS__GRUPO RETURN SYS_REFCURSOR;
	FUNCTION CO__TIENE RETURN SYS_REFCURSOR;
	FUNCTION CO__PERTENECE RETURN SYS_REFCURSOR;

	/*EQUIPO*/
	
	PROCEDURE AD_EQUIPO (xNOMBRE IN VARCHAR,xLUGAR IN NUMBER);
	PROCEDURE MOD_EQUIPO (xID_EQUIPO IN NUMBER);
	
	PROCEDURE AD_PERTENECE_EQU (xID_USUARIO IN VARCHAR,xID_EQUIPO IN NUMBER);
	FUNCTION CONS_EQUI RETURN SYS_REFCURSOR;
	FUNCTION CON_PERTENECE RETURN SYS_REFCURSOR;
  
  /*PRUEBA*/
  PROCEDURE AD_PRO  (xID_PROBLEMA  IN NUMBER,xNOMBRE  IN VARCHAR,xPDF IN  VARCHAR,xTIEMPO IN NUMBER,xMEMORIA  IN VARCHAR,xCREADOR IN VARCHAR,xTEMA  IN VARCHAR);
  FUNCTION CO_PRO RETURN SYS_REFCURSOR;
  /*CONSULTAS*/
  /*1*/
  FUNCTION CO_EQUI (xNOMBRE IN VARCHAR) RETURN SYS_REFCURSOR; 
  /*2*/
  FUNCTION CO_PRO_CO2 RETURN SYS_REFCURSOR;
  /*3*/
  FUNCTION CO_GRUPO  RETURN SYS_REFCURSOR;
  /*4*/
  FUNCTION CO_COM_CO4(xTest IN VARCHAR) RETURN SYS_REFCURSOR;
  /*5*/
  FUNCTION CO_COM_CO5(xTest IN NUMBER) RETURN SYS_REFCURSOR;
  /*6*/
  FUNCTION CO_USUA_CO6 RETURN SYS_REFCURSOR;
  /*7*/
   FUNCTION CO_USUA_CO7 RETURN SYS_REFCURSOR;
END PA_USUARIO;
/
CREATE OR REPLACE PACKAGE PA_ASOCIACION IS 
	PROCEDURE AD_ASOCIACION_USUARIO (xUSERNAME IN  VARCHAR,xNOMBRE IN  VARCHAR,xCORREO IN  VARCHAR,xFECHA  IN DATE,xTELEFONO IN  NUMBER,xOCUPACION IN  VARCHAR,xESTADO  IN VARCHAR,xLUGAR IN NUMBER,xPerfil IN XMLTYPE);
	PROCEDURE MOD_ASOCIACION_USUARIO (xUSERNAME IN  VARCHAR,xNOMBRE IN  VARCHAR,xCORREO IN  VARCHAR,xTELEFONO IN  NUMBER,xOCUPACION IN  VARCHAR,xESTADO  IN VARCHAR,xLUGAR IN NUMBER,xPerfil IN XMLTYPE);
	PROCEDURE ELI_ASOCIACION_USUARIO (xUSERNAME IN  VARCHAR);
	FUNCTION CO_ASOCIACION_USUARIOS  RETURN SYS_REFCURSOR;
	PROCEDURE AD_ASOCIACION_PROBLEMA  (xID_PROBLEMA  IN NUMBER,xNOMBRE  IN VARCHAR,xPDF IN  VARCHAR,xTIEMPO IN NUMBER,xMEMORIA  IN VARCHAR,xCREADOR IN VARCHAR,xTEMA  IN VARCHAR);
	PROCEDURE MOD_ASOCIACION_PROBLEMA (xID_PROBLEMA  IN NUMBER,xTIEMPO IN NUMBER,xMEMORIA  IN VARCHAR,xTEMA  IN VARCHAR);
	PROCEDURE ELI_ASOCIACION_PROBLEMA (xID_PROBLEMA  IN NUMBER);
	FUNCTION CO_ASOCIACION_PROBLEMA  RETURN SYS_REFCURSOR;
	PROCEDURE AD_ASOCIACION_PRUEBA (xID_PRUEBA  IN NUMBER, xINPUT_CASE  IN VARCHAR, xOUTPUT_CASE  IN VARCHAR,xPROPOSITO  IN VARCHAR,xID_PROBLEMA IN NUMBER);
	PROCEDURE MOD_ASOCIACION_PRUEBA (xID_PRUEBA  IN NUMBER, xINPUT_CASE  IN VARCHAR, xOUTPUT_CASE  IN VARCHAR,xPROPOSITO  IN VARCHAR,xID_PROBLEMA IN NUMBER);
	PROCEDURE ELI_ASOCIACION_PRUEBA (xID_PRUEBA  IN NUMBER);
	FUNCTION CO_ASOCIACION_PRUEBA  RETURN SYS_REFCURSOR;
	PROCEDURE AD_ASOCIACION_GRUPO (xNOMBRE IN VARCHAR, xCREADOR IN VARCHAR);
	PROCEDURE MOD_ASOCIACION_GRUPO (xID_GRUPO IN NUMBER, xNOMBRE IN VARCHAR);
	PROCEDURE AD_ASOCIACION_TIENE (xID_GRUPO IN NUMBER, xID_TEMA IN VARCHAR);
	PROCEDURE AD_ASOCIACION_PERTENECE (xID_USUARIO IN VARCHAR, xID_GRUPO IN NUMBER);
	PROCEDURE EL_ASOCIACION_PERTENECE (xID_USUARIO IN VARCHAR, xID_GRUPO IN NUMBER);
	FUNCTION CO_ASOCIACION_GRUPO RETURN SYS_REFCURSOR;	
	FUNCTION CONS_ASOCIOACION_GRUPO RETURN SYS_REFCURSOR;
	FUNCTION CO_ASOCIOACION_TIENE RETURN SYS_REFCURSOR;
	FUNCTION CO_ASOCIOACION_PERTENECE RETURN SYS_REFCURSOR;
	PROCEDURE AD_ASOCIACION_TEMA (xID_TEMA IN VARCHAR, xNOMBRE IN VARCHAR, xPADRE IN VARCHAR);
	FUNCTION CO_ASOCIACION_TEMA RETURN SYS_REFCURSOR;
END PA_ASOCIACION;