    CREATE TABLE version(nombre VARCHAR(5)NOT NULL,fecha DATE NOT NULL);
    CREATE TABLE segmento(nombre VARCHAR(10)NOT NULL,tipo VARCHAR NOT NULL,);
    CREATE TABLE punto(orden INTEGER NOT NULL,nombre VARCHAR(10)NOT NULL,tipo VARCHAR NOT NULL,distancia FLOAT NOT NULL,tiempoLimite INTEGER NOT NULL,