--CREAR TABLAS 

CREATE TABLE MARCA(
    NOMBRE VARCHAR2(32) NOT NULL
);  

CREATE TABLE VALORACION(
    ID NUMBER(4) NOT NULL,
    PRECIO NUMBER(10,2) NOT NULL,
    FECHA DATE NOT NULL,
    ESTADO VARCHAR2(1) NOT NULL,
    VEHICULO VARCHAR2(15) NOT NULL
);

CREATE TABLE VEHICULO (
    VIN VARCHAR2(15) NOT NULL,
    FECHA DATE NOT NULL,
    MODELO VARCHAR(10) NOT NULL,
    COLOR VARCHAR2(8) NOT NULL,
    TIPO VARCHAR2(10) NOT NULL,
    MARCA VARCHAR(32) NOT NULL,
    CONDUCTOR NUMBER(5) NOT NULL,
    POLIZA NUMBER(10) NOT NULL
);



CREATE TABLE CONDUCTOR(
    ID NUMBER(5) NOT NULL,
    NOMBRE VARCHAR2(64) NOT NULL,
    DIRECCION VARCHAR2(20) NOT NULL,    
    TELEFONO NUMBER(10),
    CIUDAD VARCHAR(20) NOT NULL,
    EMAIL VARCHAR2(30) NOT NULL,
    REGISTRO NUMBER(10) NOT NULL
);

CREATE TABLE UBICACION(
    ID NUMBER(10) NOT NULL,
    LONGITUD NUMBER(3,6) NOT NULL,
    LATITUD NUMBER(3,6) NOT NULL,
    CIUDAD VARCHAR2(20) NOT NULL,
    PAIS VARCHAR2(20) NOT NULL,
    DIRECCION VARCHAR2(20)
);



CREATE TABLE RECLAMO (
    ID NUMBER(10) NOT NULL,
    FECHA DATE NOT NULL,
    DETALLE VARCHAR2(100)NOT NULL,
    VALOR NUMBER(10,2) NOT NULL,
    UBICACION NUMBER(10)NOT NULL,
    VEHICULO VARCHAR(15) NOT NULL,
    CONDUCTOR NUMBER(5) NOT NULL,
    POLIZA NUMBER(5) NOT NULL,
    VENDEDOR NUMBER(5) NOT NULL
);



CREATE TABLE POLIZA(
    ID NUMBER(10) NOT NULL,
    DEDUCIBLE NUMBER(10,2) NOT NULL,
    VENDEDOR NUMBER(5)  NOT NULL,
    REGISTRO NUMBER(10)  NOT NULL,   
    COBERTURA NUMBER(5) NOT NULL,
    PROYECTO NUMBER(10) NOT NULL
);

CREATE TABLE COBERTURA(
    ID NUMBER(5) NOT NULL,
    MONTOHURTO NUMBER(10) NOT NULL,
    MONTODANO NUMBER(10) NOT NULL,
    RCIVIL NUMBER(10) NOT NULL
);



CREATE TABLE REGISTRO(
    RNUMERO NUMBER(10) NOT NULL,
    PUNTOATENCION NUMBER(10) NOT NULL,
    ADMINISTRADOR NUMBER(5) NOT NULL
);

CREATE TABLE PUNTOATENCION
(
    ID NUMBER(10) NOT NULL,
    UBICACION NUMBER(10) NOT NULL
);

CREATE TABLE ADMINISTRADOR(
    ID NUMBER(5) NOT NULL,
    NOMBRE VARCHAR2(20) NOT NULL,
    TELEFONO NUMBER(10) NOT NULL,
    EMAIL VARCHAR2(30) NOT NULL
);

CREATE TABLE VENDEDOR(
    ID NUMBER(5) NOT NULL,
    NOMBRE VARCHAR2(32) NOT NULL,
    SALARIO NUMBER(10,2) NOT NULL,
    EMAIL VARCHAR2(30) NOT NULL,
    FECHAENTRADA DATE NOT NULL
);


CREATE TABLE PROYECTO(
   ID NUMBER(10) NOT NULL,
   NOMBRE VARCHAR2(20) NOT NULL,
   FECHAINICIO DATE NOT NULL,
   FECHAFIN DATE NOT NULL,
   POLIZA NUMBER(10) NOT NULL,
   VENDEDOR NUMBER(5) NOT NULL
);

