CREATE ROLE USUARIO;
DROP ROLE USUARIO;
CREATE ROLE ASOCIACION;
DROP ROLE ASOCIACION;
CREATE ROLE ADMINISTRADOR;
DROP ROLE ADMINISTRADOR;
CREATE ROLE LIDER_EQUIPO;
DROP ROLE LIDER_EQUIPO;

GRANT EXECUTE ON PA_USUARIO TO USUARIO;

REVOKE EXECUTE ON PA_USUARIO FROM USUARIO;

GRANT EXECUTE ON PA_ASOCIACION TO ASOCIACION;

REVOKE EXECUTE ON PA_ASOCIACION FROM ASOCIACION;

GRANT EXECUTE ON PA_ADMIN TO ADMINISTRADOR;

REVOKE EXECUTE ON PA_ADMIN FROM ADMINISTRADOR;

GRANT EXECUTE ON PA_LIDER_EQUIPO TO LIDER_EQUIPO;

REVOKE EXECUTE ON PA_LIDER_EQUIPO FROM LIDER_EQUIPO;

