ALTER TABLE GRUPOS ADD CONSTRAINT
 UK_GRUPOS_nombre UNIQUE(nombre);

ALTER TABLE USUARIOS ADD CONSTRAINT
 UK_USUARIOS_correo UNIQUE(correo);

ALTER TABLE USUARIOS ADD CONSTRAINT
 UK_USUARIOS_telefono UNIQUE(telefono);

ALTER TABLE PROBLEMAS ADD CONSTRAINT
 UK_PROBLEMAS_nombre UNIQUE(nombre);

ALTER TABLE PROBLEMAS ADD CONSTRAINT
 UK_PROBLEMAS_pdf UNIQUE(pdf);

ALTER TABLE PRUEBAS ADD CONSTRAINT
 UK_PRUEBAS_INPUT_CASE UNIQUE(INPUT_CASE);
 
ALTER TABLE PRUEBAS ADD CONSTRAINT
 UK_PRUEBAS_OUTPUT_CASE UNIQUE(OUTPUT_CASE);
