/*ELIMINAR TABLAS*/
DROP TABLE COMENTARIOS;
DROP TABLE PRUEBAS;
DROP TABLE PERTENECE_EQUIPO;
DROP TABLE PERTENECE_GRUPO;
DROP TABLE EQUIPOS;
DROP TABLE GRUPO_TIENE_TEMA;
DROP TABLE GRUPOS;
DROP TABLE PROBLEMAS;
DROP TABLE TEMAS;
DROP TABLE USUARIOS;
DROP TABLE LUGARES;