/*pk*/
ALTER TABLE Veredictos ADD CONSTRAINT PK_VEREDCITOS
 PRIMARY KEY(ID_veredicto);
 
ALTER TABLE ASISTE ADD CONSTRAINT PK_ASISTE
 PRIMARY KEY(EQUIPO,EVENTO);
 

 
ALTER TABLE INSCRIPCIONES ADD CONSTRAINT PK_INSCRIPCIONES
 PRIMARY KEY(ID_INSCRIPCION);

ALTER TABLE ASOCIACIONES ADD CONSTRAINT PK_ASOCIACIONES
 PRIMARY KEY(ID_ASOCIACION);


ALTER TABLE SCOREBOARD ADD CONSTRAINT PK_SCOREBOARD
 PRIMARY KEY(EQUIPO,ID_EVENTO);

ALTER TABLE TIENE ADD CONSTRAINT PK_TIENE
 PRIMARY KEY(ID_PROBLEMA,ID_EVENTO);

ALTER TABLE EVENTOS ADD CONSTRAINT PK_EVENTO
 PRIMARY KEY(ID_EVENTO);


ALTER TABLE realizan ADD CONSTRAINT PK_REALIZAN
 PRIMARY KEY(ID_EVENTO,ID_ASOCIACION);
 
ALTER TABLE ENVIOS ADD CONSTRAINT PK_ENVIOS
 PRIMARY KEY(ID_envio);