/*Disparadores OK*/
INSERT INTO INSCRIPCIONES values(10,12,SYSDATE,2,10);
INSERT INTO ENVIOS VALUES(1,919,6,1,'C++');


INSERT INTO EVENTOS VALUES('ACM','Dificil',6,TO_DATE('2017/08/12','yyyy/mm/dd'),null,8,'Maraton',10000,1,0);
INSERT INTO REALIZAN VALUES(6,3);

INSERT INTO INSCRIPCIONES values(1,seq_inscripcion.nextval,SYSDATE,2,6);
INSERT INTO INSCRIPCIONES values(10000,seq_inscripcion.nextval,SYSDATE,2,6);
INSERT INTO INSCRIPCIONES values(10000,seq_inscripcion.nextval,SYSDATE,1,6);
INSERT INTO INSCRIPCIONES values(10000,seq_inscripcion.nextval,SYSDATE,3,6);
INSERT INTO INSCRIPCIONES values(10000,seq_inscripcion.nextval,SYSDATE,4,6);
INSERT INTO INSCRIPCIONES values(10000,seq_inscripcion.nextval,SYSDATE,5,6);
INSERT INTO INSCRIPCIONES values(10000,seq_inscripcion.nextval,SYSDATE,6,6);
INSERT INTO INSCRIPCIONES values(10000,seq_inscripcion.nextval,SYSDATE,7,6);
INSERT INTO INSCRIPCIONES values(10000,seq_inscripcion.nextval,SYSDATE,10,6);.
INSERT INTO INSCRIPCIONES values(10000,seq_inscripcion.nextval,SYSDATE,8,6);

DELETE FROM ASOCIACIONES WHERE ID_ASOCIACION = 1;

INSERT INTO TIENE VALUES(824,6);
INSERT INTO ENVIOS VALUES(seq_envios.nextval,829,7,6,'C++');
