insert into cadena (idCadena, nombre) values (1, 'Hackett Inc');
insert into cadena (idCadena, nombre) values (2, 'Purdy, Dietrich and Sauer');
insert into cadena (idCadena, nombre) values (3, 'Yundt Inc');
insert into cadena (idCadena, nombre) values (4, 'D''Amore Group');
insert into cadena (idCadena, nombre) values (5, 'McKenzie Group');
insert into cadena (idCadena, nombre) values (6, 'MacGyver, Streich and Blanda');
insert into cadena (idCadena, nombre) values (7, 'Kihn and Sons');
insert into cadena (idCadena, nombre) values (8, 'Wilkinson, Barton and Braun');
insert into cadena (idCadena, nombre) values (9, 'Herzog, Keebler and Ankunding');
insert into cadena (idCadena, nombre) values (10, 'Hackett Inc');
insert into cadena (idCadena, nombre) values (11, 'Ratke, Mertz and Kuphal');
insert into cadena (idCadena, nombre) values (12, 'Stracke-Deckow');
insert into cadena (idCadena, nombre) values (13, 'Heller-Simonis');
insert into cadena (idCadena, nombre) values (14, 'Roob Inc');
insert into cadena (idCadena, nombre) values (15, 'West Inc');
insert into cadena (idCadena, nombre) values (16, 'Romaguera, Hyatt and Emard');
insert into cadena (idCadena, nombre) values (17, 'Hills, Veum and Powlowski');
insert into cadena (idCadena, nombre) values (18, 'Reichert, Runolfsdottir and Sporer');
insert into cadena (idCadena, nombre) values (19, 'Goldner, Bernhard and Spencer');
insert into cadena (idCadena, nombre) values (20, 'Brown and Sons');
insert into cadena (idCadena, nombre) values (21, 'Ferry, Goldner and Koch');
insert into cadena (idCadena, nombre) values (22, 'Herzog Inc');
insert into cadena (idCadena, nombre) values (23, 'Osinski Inc');
insert into cadena (idCadena, nombre) values (24, 'Runte-Lesch');
insert into cadena (idCadena, nombre) values (25, 'Moore and Sons');
insert into cadena (idCadena, nombre) values (26, 'Terry and Sons');
insert into cadena (idCadena, nombre) values (27, 'Roob, Krajcik and Kilback');
insert into cadena (idCadena, nombre) values (28, 'Sanford-Ritchie');
insert into cadena (idCadena, nombre) values (29, 'Klocko, Boyle and Heathcote');
insert into cadena (idCadena, nombre) values (30, 'Mertz-Cassin');
insert into cadena (idCadena, nombre) values (31, 'Gorczany Group');
insert into cadena (idCadena, nombre) values (32, 'Bauch, Upton and Osinski');
insert into cadena (idCadena, nombre) values (33, 'Greenfelder and Sons');
insert into cadena (idCadena, nombre) values (34, 'Kihn-Funk');
insert into cadena (idCadena, nombre) values (35, 'Koepp Group');
insert into cadena (idCadena, nombre) values (36, 'Lehner-Cole');
insert into cadena (idCadena, nombre) values (37, 'Crooks, Will and Baumbach');
insert into cadena (idCadena, nombre) values (38, 'Jenkins, Jaskolski and Gutkowski');
insert into cadena (idCadena, nombre) values (39, 'Mayert LLC');
insert into cadena (idCadena, nombre) values (40, 'Wisozk-Hackett');
insert into cadena (idCadena, nombre) values (41, 'D''Amore, Kuhlman and Lockman');
insert into cadena (idCadena, nombre) values (42, 'Shanahan Inc');
insert into cadena (idCadena, nombre) values (43, 'Zemlak-Gleason');
insert into cadena (idCadena, nombre) values (44, 'Bode-Connelly');
insert into cadena (idCadena, nombre) values (45, 'Cole-Howe');
insert into cadena (idCadena, nombre) values (46, 'Klein, Rath and Farrell');
insert into cadena (idCadena, nombre) values (47, 'Vandervort-Krajcik');
insert into cadena (idCadena, nombre) values (48, 'Nader, Pouros and Heathcote');
insert into cadena (idCadena, nombre) values (49, 'Veum, Heidenreich and Wunsch');
insert into cadena (idCadena, nombre) values (50, 'Keebler-Schuster');
insert into cadena (idCadena, nombre) values (51, 'Hills-Schaefer');
insert into cadena (idCadena, nombre) values (52, 'Walsh-O''Conner');
insert into cadena (idCadena, nombre) values (53, 'Thompson-Sawayn');
insert into cadena (idCadena, nombre) values (54, 'Casper-Bogan');
insert into cadena (idCadena, nombre) values (55, 'Runolfsdottir LLC');
insert into cadena (idCadena, nombre) values (56, 'Hayes Group');
insert into cadena (idCadena, nombre) values (57, 'Mertz and Sons');
insert into cadena (idCadena, nombre) values (58, 'Fadel-Bogisich');
insert into cadena (idCadena, nombre) values (59, 'Windler, Legros and Cruickshank');
insert into cadena (idCadena, nombre) values (60, 'Gorczany LLC');
insert into cadena (idCadena, nombre) values (61, 'Ryan-Satterfield');
insert into cadena (idCadena, nombre) values (62, 'O''Hara-Runolfsdottir');
insert into cadena (idCadena, nombre) values (63, 'Heathcote Group');
insert into cadena (idCadena, nombre) values (64, 'Armstrong and Sons');
insert into cadena (idCadena, nombre) values (65, 'Abernathy and Sons');
insert into cadena (idCadena, nombre) values (66, 'Mann, Treutel and Marquardt');
insert into cadena (idCadena, nombre) values (67, 'Hayes Group');
insert into cadena (idCadena, nombre) values (68, 'Quitzon, Greenfelder and Bergnaum');
insert into cadena (idCadena, nombre) values (69, 'Klein, Schuster and McKenzie');
insert into cadena (idCadena, nombre) values (70, 'Casper-Leuschke');
insert into cadena (idCadena, nombre) values (71, 'Johns, Sauer and Kuphal');
insert into cadena (idCadena, nombre) values (72, 'Carroll LLC');
insert into cadena (idCadena, nombre) values (73, 'Cormier and Sons');
insert into cadena (idCadena, nombre) values (74, 'Kshlerin Group');
insert into cadena (idCadena, nombre) values (75, 'Klocko Inc');
insert into cadena (idCadena, nombre) values (76, 'King Inc');
insert into cadena (idCadena, nombre) values (77, 'Rippin Group');
insert into cadena (idCadena, nombre) values (78, 'Daniel, Bahringer and Klocko');
insert into cadena (idCadena, nombre) values (79, 'Gleason Inc');
insert into cadena (idCadena, nombre) values (80, 'Smitham, Herzog and O''Keefe');
insert into cadena (idCadena, nombre) values (81, 'Kessler-Champlin');
insert into cadena (idCadena, nombre) values (82, 'Buckridge Group');
insert into cadena (idCadena, nombre) values (83, 'Balistreri Group');
insert into cadena (idCadena, nombre) values (84, 'Kuhlman Group');
insert into cadena (idCadena, nombre) values (85, 'Smith-Gleason');
insert into cadena (idCadena, nombre) values (86, 'Hansen-Roob');
insert into cadena (idCadena, nombre) values (87, 'Becker-Dare');
insert into cadena (idCadena, nombre) values (88, 'Shanahan, Schmidt and Hayes');
insert into cadena (idCadena, nombre) values (89, 'Raynor, Wunsch and Wuckert');
insert into cadena (idCadena, nombre) values (90, 'Zboncak Inc');
insert into cadena (idCadena, nombre) values (91, 'O''Keefe, Willms and Gaylord');
insert into cadena (idCadena, nombre) values (92, 'Dicki Group');
insert into cadena (idCadena, nombre) values (93, 'Kub-Gibson');
insert into cadena (idCadena, nombre) values (94, 'Reichel and Sons');
insert into cadena (idCadena, nombre) values (95, 'Schroeder, Koelpin and Nader');
insert into cadena (idCadena, nombre) values (96, 'Ledner-Bailey');
insert into cadena (idCadena, nombre) values (97, 'Crist, Schulist and Stark');
insert into cadena (idCadena, nombre) values (98, 'Mayert-Halvorson');
insert into cadena (idCadena, nombre) values (99, 'Smith, Hahn and Willms');
insert into cadena (idCadena, nombre) values (100, 'Stoltenberg, Stoltenberg and Effertz');
insert into cadena (idCadena, nombre) values (101, 'Stracke, Lubowitz and Huel');
insert into cadena (idCadena, nombre) values (102, 'Parker, Muller and Reilly');
insert into cadena (idCadena, nombre) values (103, 'Ernser, Satterfield and Nolan');
insert into cadena (idCadena, nombre) values (104, 'Mayert-Leffler');
insert into cadena (idCadena, nombre) values (105, 'Mante Group');
insert into cadena (idCadena, nombre) values (106, 'Konopelski-Gottlieb');
insert into cadena (idCadena, nombre) values (107, 'Williamson-Runolfsdottir');
insert into cadena (idCadena, nombre) values (108, 'Lemke Group');
insert into cadena (idCadena, nombre) values (109, 'Bradtke, Keeling and Koepp');
insert into cadena (idCadena, nombre) values (110, 'Schneider Inc');
insert into cadena (idCadena, nombre) values (111, 'Simonis, Harris and Vandervort');
insert into cadena (idCadena, nombre) values (112, 'Schaden and Sons');
insert into cadena (idCadena, nombre) values (113, 'Aufderhar, Bednar and Wilkinson');
insert into cadena (idCadena, nombre) values (114, 'O''Kon LLC');
insert into cadena (idCadena, nombre) values (115, 'Daniel, Walter and Rolfson');
insert into cadena (idCadena, nombre) values (116, 'Schmeler, Yundt and Rogahn');
insert into cadena (idCadena, nombre) values (117, 'Stiedemann, Thompson and Weber');
insert into cadena (idCadena, nombre) values (118, 'Gutkowski LLC');
insert into cadena (idCadena, nombre) values (119, 'Lueilwitz, Reichel and Nienow');
insert into cadena (idCadena, nombre) values (120, 'Wyman-Bosco');
insert into cadena (idCadena, nombre) values (121, 'Brown, Bogan and Klein');
insert into cadena (idCadena, nombre) values (122, 'Towne and Sons');
insert into cadena (idCadena, nombre) values (123, 'Tillman Inc');
insert into cadena (idCadena, nombre) values (124, 'Ankunding, Jaskolski and Waelchi');
insert into cadena (idCadena, nombre) values (125, 'Schuster-Predovic');
insert into cadena (idCadena, nombre) values (126, 'Kirlin-Turcotte');
insert into cadena (idCadena, nombre) values (127, 'Collier, Pfeffer and Conroy');
insert into cadena (idCadena, nombre) values (128, 'Veum Inc');
insert into cadena (idCadena, nombre) values (129, 'Schneider-Jones');
insert into cadena (idCadena, nombre) values (130, 'Wisozk Inc');
insert into cadena (idCadena, nombre) values (131, 'Bashirian, Feil and Blick');
insert into cadena (idCadena, nombre) values (132, 'Glover-Senger');
insert into cadena (idCadena, nombre) values (133, 'MacGyver-Frami');
insert into cadena (idCadena, nombre) values (134, 'Kerluke and Sons');
insert into cadena (idCadena, nombre) values (135, 'McDermott Inc');
insert into cadena (idCadena, nombre) values (136, 'Muller, Hilpert and Christiansen');
insert into cadena (idCadena, nombre) values (137, 'Swift LLC');
insert into cadena (idCadena, nombre) values (138, 'Prosacco, Moore and Hoeger');
insert into cadena (idCadena, nombre) values (139, 'Wilkinson-Osinski');
insert into cadena (idCadena, nombre) values (140, 'Osinski LLC');
insert into cadena (idCadena, nombre) values (141, 'Hirthe, Rowe and Leffler');
insert into cadena (idCadena, nombre) values (142, 'Graham LLC');
insert into cadena (idCadena, nombre) values (143, 'Hilpert Group');
insert into cadena (idCadena, nombre) values (144, 'Windler Inc');
insert into cadena (idCadena, nombre) values (145, 'Grady, O''Keefe and Schulist');
insert into cadena (idCadena, nombre) values (146, 'Aufderhar-Streich');
insert into cadena (idCadena, nombre) values (147, 'Pagac-Botsford');
insert into cadena (idCadena, nombre) values (148, 'Kemmer Group');
insert into cadena (idCadena, nombre) values (149, 'Wisoky Inc');
insert into cadena (idCadena, nombre) values (150, 'Kuphal-Kulas');
insert into cadena (idCadena, nombre) values (151, 'Watsica, Baumbach and Herman');
insert into cadena (idCadena, nombre) values (152, 'Ondricka Group');
insert into cadena (idCadena, nombre) values (153, 'O''Hara LLC');
insert into cadena (idCadena, nombre) values (154, 'Price, Schneider and Donnelly');
insert into cadena (idCadena, nombre) values (155, 'O''Kon-Thompson');
insert into cadena (idCadena, nombre) values (156, 'Dibbert, Kessler and Hoeger');
insert into cadena (idCadena, nombre) values (157, 'Greenholt-Ritchie');
insert into cadena (idCadena, nombre) values (158, 'Cole-Bosco');
insert into cadena (idCadena, nombre) values (159, 'Casper, Robel and Walker');
insert into cadena (idCadena, nombre) values (160, 'Heathcote-Baumbach');
insert into cadena (idCadena, nombre) values (161, 'McDermott, Gulgowski and Von');
insert into cadena (idCadena, nombre) values (162, 'Luettgen Inc');
insert into cadena (idCadena, nombre) values (163, 'Steuber-Bergstrom');
insert into cadena (idCadena, nombre) values (164, 'Larkin, Dickens and Robel');
insert into cadena (idCadena, nombre) values (165, 'Kiehn Group');
insert into cadena (idCadena, nombre) values (166, 'Borer, Gislason and Gottlieb');
insert into cadena (idCadena, nombre) values (167, 'Connelly-Schamberger');
insert into cadena (idCadena, nombre) values (168, 'Schinner, Turner and Connelly');
insert into cadena (idCadena, nombre) values (169, 'Lind-Lebsack');
insert into cadena (idCadena, nombre) values (170, 'Vandervort-Ledner');
insert into cadena (idCadena, nombre) values (171, 'Sipes LLC');
insert into cadena (idCadena, nombre) values (172, 'Kovacek, Braun and Barton');
insert into cadena (idCadena, nombre) values (173, 'Hermann-Harber');
insert into cadena (idCadena, nombre) values (174, 'Crooks Inc');
insert into cadena (idCadena, nombre) values (175, 'Corkery, Yundt and King');
insert into cadena (idCadena, nombre) values (176, 'Lehner Inc');
insert into cadena (idCadena, nombre) values (177, 'Lind-Kulas');
insert into cadena (idCadena, nombre) values (178, 'Lockman Inc');
insert into cadena (idCadena, nombre) values (179, 'Senger, Yundt and Nitzsche');
insert into cadena (idCadena, nombre) values (180, 'Tremblay-Mayert');
insert into cadena (idCadena, nombre) values (181, 'Gibson LLC');
insert into cadena (idCadena, nombre) values (182, 'McGlynn Group');
insert into cadena (idCadena, nombre) values (183, 'Schiller-Bednar');
insert into cadena (idCadena, nombre) values (184, 'Kohler-Prohaska');
insert into cadena (idCadena, nombre) values (185, 'Bartoletti-Legros');
insert into cadena (idCadena, nombre) values (186, 'Schmitt Inc');
insert into cadena (idCadena, nombre) values (187, 'Swaniawski-Romaguera');
insert into cadena (idCadena, nombre) values (188, 'Doyle Group');
insert into cadena (idCadena, nombre) values (189, 'Altenwerth, VonRueden and Kutch');
insert into cadena (idCadena, nombre) values (190, 'Schaefer-Maggio');
insert into cadena (idCadena, nombre) values (191, 'Wehner-Hettinger');
insert into cadena (idCadena, nombre) values (192, 'Crooks-Kuhn');
insert into cadena (idCadena, nombre) values (193, 'West, Goodwin and Kozey');
insert into cadena (idCadena, nombre) values (194, 'Rosenbaum, Donnelly and Keebler');
insert into cadena (idCadena, nombre) values (195, 'Altenwerth, Kertzmann and Adams');
insert into cadena (idCadena, nombre) values (196, 'Greenholt, Vandervort and Spinka');
insert into cadena (idCadena, nombre) values (197, 'O''Connell, Bernier and Fay');
insert into cadena (idCadena, nombre) values (198, 'Kihn, Brown and Kemmer');
insert into cadena (idCadena, nombre) values (199, 'Kris-Daugherty');
insert into cadena (idCadena, nombre) values (200, 'Lesch LLC');
insert into cadena (idCadena, nombre) values (201, 'Hills, Kuvalis and Rath');
insert into cadena (idCadena, nombre) values (202, 'Christiansen, Kassulke and Koss');
insert into cadena (idCadena, nombre) values (203, 'Bradtke, O''Kon and Rippin');
insert into cadena (idCadena, nombre) values (204, 'Ledner-Watsica');
insert into cadena (idCadena, nombre) values (205, 'Kautzer-Schmitt');
insert into cadena (idCadena, nombre) values (206, 'Feest Inc');
insert into cadena (idCadena, nombre) values (207, 'Kuhn LLC');
insert into cadena (idCadena, nombre) values (208, 'Harvey, Trantow and Stracke');
insert into cadena (idCadena, nombre) values (209, 'Goldner-Wehner');
insert into cadena (idCadena, nombre) values (210, 'Lindgren-Waelchi');
insert into cadena (idCadena, nombre) values (211, 'Reinger, Mante and Mayer');
insert into cadena (idCadena, nombre) values (212, 'Batz Inc');
insert into cadena (idCadena, nombre) values (213, 'Crist-Friesen');
insert into cadena (idCadena, nombre) values (214, 'Fahey Group');
insert into cadena (idCadena, nombre) values (215, 'Gaylord-Stokes');
insert into cadena (idCadena, nombre) values (216, 'Dooley-Parisian');
insert into cadena (idCadena, nombre) values (217, 'Waelchi, Pfeffer and Kessler');
insert into cadena (idCadena, nombre) values (218, 'Littel-Powlowski');
insert into cadena (idCadena, nombre) values (219, 'Senger, Klein and Keebler');
insert into cadena (idCadena, nombre) values (220, 'Pfeffer, Kub and Adams');
insert into cadena (idCadena, nombre) values (221, 'Pouros-Mayert');
insert into cadena (idCadena, nombre) values (222, 'Tillman, Gibson and O''Kon');
insert into cadena (idCadena, nombre) values (223, 'Adams and Sons');
insert into cadena (idCadena, nombre) values (224, 'Crooks, Becker and Howell');
insert into cadena (idCadena, nombre) values (225, 'Torphy-Schumm');
insert into cadena (idCadena, nombre) values (226, 'Koch Group');
insert into cadena (idCadena, nombre) values (227, 'Walsh LLC');
insert into cadena (idCadena, nombre) values (228, 'Spencer LLC');
insert into cadena (idCadena, nombre) values (229, 'Watsica-Bergstrom');
insert into cadena (idCadena, nombre) values (230, 'Yundt, O''Keefe and Torphy');
insert into cadena (idCadena, nombre) values (231, 'Ankunding, McLaughlin and Brakus');
insert into cadena (idCadena, nombre) values (232, 'Borer and Sons');
insert into cadena (idCadena, nombre) values (233, 'Block LLC');
insert into cadena (idCadena, nombre) values (234, 'Bogisich, Gottlieb and O''Connell');
insert into cadena (idCadena, nombre) values (235, 'Rohan Inc');
insert into cadena (idCadena, nombre) values (236, 'Runolfsdottir-Hand');
insert into cadena (idCadena, nombre) values (237, 'Gislason-Thiel');
insert into cadena (idCadena, nombre) values (238, 'Tromp Group');
insert into cadena (idCadena, nombre) values (239, 'Schmeler, Douglas and Cummerata');
insert into cadena (idCadena, nombre) values (240, 'Schmeler, Dietrich and Gaylord');
insert into cadena (idCadena, nombre) values (241, 'Marvin, Runolfsdottir and Cronin');
insert into cadena (idCadena, nombre) values (242, 'Kunze Group');
insert into cadena (idCadena, nombre) values (243, 'Monahan-Swaniawski');
insert into cadena (idCadena, nombre) values (244, 'Bahringer and Sons');
insert into cadena (idCadena, nombre) values (245, 'Schneider LLC');
insert into cadena (idCadena, nombre) values (246, 'Ryan, Kemmer and Marvin');
insert into cadena (idCadena, nombre) values (247, 'Durgan, Reinger and Hilll');
insert into cadena (idCadena, nombre) values (248, 'Walker, Blick and Mosciski');
insert into cadena (idCadena, nombre) values (249, 'Kutch, Mraz and Wisoky');
insert into cadena (idCadena, nombre) values (250, 'Bradtke LLC');
insert into cadena (idCadena, nombre) values (251, 'DuBuque LLC');
insert into cadena (idCadena, nombre) values (252, 'Monahan LLC');
insert into cadena (idCadena, nombre) values (253, 'Hermann-Jerde');
insert into cadena (idCadena, nombre) values (254, 'Rosenbaum, Deckow and Hayes');
insert into cadena (idCadena, nombre) values (255, 'Considine-Schulist');
insert into cadena (idCadena, nombre) values (256, 'MacGyver-Murazik');
insert into cadena (idCadena, nombre) values (257, 'Maggio, Krajcik and Becker');
insert into cadena (idCadena, nombre) values (258, 'Kassulke and Sons');
insert into cadena (idCadena, nombre) values (259, 'Spinka, Raynor and Bruen');
insert into cadena (idCadena, nombre) values (260, 'Fay and Sons');
insert into cadena (idCadena, nombre) values (261, 'Graham Group');
insert into cadena (idCadena, nombre) values (262, 'DuBuque LLC');
insert into cadena (idCadena, nombre) values (263, 'Jacobson, Lubowitz and Sipes');
insert into cadena (idCadena, nombre) values (264, 'Marvin and Sons');
insert into cadena (idCadena, nombre) values (265, 'Leuschke-Stokes');
insert into cadena (idCadena, nombre) values (266, 'Larkin, Dietrich and Cronin');
insert into cadena (idCadena, nombre) values (267, 'Friesen, O''Kon and DuBuque');
insert into cadena (idCadena, nombre) values (268, 'Zemlak, Zboncak and Block');
insert into cadena (idCadena, nombre) values (269, 'Hintz LLC');
insert into cadena (idCadena, nombre) values (270, 'Zieme-Kunze');
insert into cadena (idCadena, nombre) values (271, 'Runolfsson and Sons');
insert into cadena (idCadena, nombre) values (272, 'Veum and Sons');
insert into cadena (idCadena, nombre) values (273, 'Howell, Dietrich and Keeling');
insert into cadena (idCadena, nombre) values (274, 'Barton LLC');
insert into cadena (idCadena, nombre) values (275, 'McDermott-Graham');
insert into cadena (idCadena, nombre) values (276, 'Ferry, Weissnat and Stokes');
insert into cadena (idCadena, nombre) values (277, 'Marks-Welch');
insert into cadena (idCadena, nombre) values (278, 'Hilpert-Heathcote');
insert into cadena (idCadena, nombre) values (279, 'Fay-Gusikowski');
insert into cadena (idCadena, nombre) values (280, 'Hammes and Sons');
insert into cadena (idCadena, nombre) values (281, 'Runolfsdottir, Upton and Pouros');
insert into cadena (idCadena, nombre) values (282, 'Smith, Pfeffer and Hilpert');
insert into cadena (idCadena, nombre) values (283, 'Rodriguez Group');
insert into cadena (idCadena, nombre) values (284, 'Sporer, Gorczany and Schimmel');
insert into cadena (idCadena, nombre) values (285, 'Parisian, Hudson and Smith');
insert into cadena (idCadena, nombre) values (286, 'White, Mayer and Rogahn');
insert into cadena (idCadena, nombre) values (287, 'Bernhard, Morissette and Kreiger');
insert into cadena (idCadena, nombre) values (288, 'Balistreri, Fadel and Fadel');
insert into cadena (idCadena, nombre) values (289, 'Ebert and Sons');
insert into cadena (idCadena, nombre) values (290, 'O''Connell and Sons');
insert into cadena (idCadena, nombre) values (291, 'Ratke and Sons');
insert into cadena (idCadena, nombre) values (292, 'Kuvalis-VonRueden');
insert into cadena (idCadena, nombre) values (293, 'McLaughlin Group');
insert into cadena (idCadena, nombre) values (294, 'Carroll, Bradtke and Luettgen');
insert into cadena (idCadena, nombre) values (295, 'Nicolas, Shanahan and Kub');
insert into cadena (idCadena, nombre) values (296, 'Lind LLC');
insert into cadena (idCadena, nombre) values (297, 'MacGyver LLC');
insert into cadena (idCadena, nombre) values (298, 'Oberbrunner, Koepp and Heathcote');
insert into cadena (idCadena, nombre) values (299, 'Bogisich and Sons');
insert into cadena (idCadena, nombre) values (300, 'Hansen-Thompson');
insert into cadena (idCadena, nombre) values (301, 'Hand-Schiller');
insert into cadena (idCadena, nombre) values (302, 'Bahringer-Collins');
insert into cadena (idCadena, nombre) values (303, 'MacGyver, Hilpert and Simonis');
insert into cadena (idCadena, nombre) values (304, 'Lubowitz LLC');
insert into cadena (idCadena, nombre) values (305, 'Lemke-Weber');
insert into cadena (idCadena, nombre) values (306, 'Prosacco, Cummerata and Bosco');
insert into cadena (idCadena, nombre) values (307, 'Mohr, Brekke and Keeling');
insert into cadena (idCadena, nombre) values (308, 'Smitham LLC');
insert into cadena (idCadena, nombre) values (309, 'Rippin Inc');
insert into cadena (idCadena, nombre) values (310, 'Bahringer and Sons');
insert into cadena (idCadena, nombre) values (311, 'Windler-Kreiger');
insert into cadena (idCadena, nombre) values (312, 'Goodwin Inc');
insert into cadena (idCadena, nombre) values (313, 'Mills Inc');
insert into cadena (idCadena, nombre) values (314, 'Erdman-Auer');
insert into cadena (idCadena, nombre) values (315, 'Hoeger Group');
insert into cadena (idCadena, nombre) values (316, 'Schinner-Shanahan');
insert into cadena (idCadena, nombre) values (317, 'Schuster Inc');
insert into cadena (idCadena, nombre) values (318, 'Becker-Blick');
insert into cadena (idCadena, nombre) values (319, 'Schiller LLC');
insert into cadena (idCadena, nombre) values (320, 'Oberbrunner, Eichmann and Gislason');
insert into cadena (idCadena, nombre) values (321, 'Wehner-Doyle');
insert into cadena (idCadena, nombre) values (322, 'Waelchi-Bernhard');
insert into cadena (idCadena, nombre) values (323, 'Gulgowski and Sons');
insert into cadena (idCadena, nombre) values (324, 'Bartoletti LLC');
insert into cadena (idCadena, nombre) values (325, 'Olson-Kilback');
insert into cadena (idCadena, nombre) values (326, 'Adams and Sons');
insert into cadena (idCadena, nombre) values (327, 'Connelly-Hagenes');
insert into cadena (idCadena, nombre) values (328, 'Dietrich, Gottlieb and Lueilwitz');
insert into cadena (idCadena, nombre) values (329, 'Dicki, Farrell and Casper');
insert into cadena (idCadena, nombre) values (330, 'Blanda-Heathcote');
insert into cadena (idCadena, nombre) values (331, 'Witting-Graham');
insert into cadena (idCadena, nombre) values (332, 'Waters, Kulas and Witting');
insert into cadena (idCadena, nombre) values (333, 'Watsica, O''Kon and Schumm');
insert into cadena (idCadena, nombre) values (334, 'Hermann-Shields');
insert into cadena (idCadena, nombre) values (335, 'Little, Streich and Smith');
insert into cadena (idCadena, nombre) values (336, 'Swift, Bernhard and Yundt');
insert into cadena (idCadena, nombre) values (337, 'Murray, Rodriguez and Gutmann');
insert into cadena (idCadena, nombre) values (338, 'Bogisich Inc');
insert into cadena (idCadena, nombre) values (339, 'Ledner-Wunsch');
insert into cadena (idCadena, nombre) values (340, 'Franecki and Sons');
insert into cadena (idCadena, nombre) values (341, 'Ward Inc');
insert into cadena (idCadena, nombre) values (342, 'Welch, Windler and Effertz');
insert into cadena (idCadena, nombre) values (343, 'Balistreri-Hirthe');
insert into cadena (idCadena, nombre) values (344, 'Keeling, Leuschke and Bashirian');
insert into cadena (idCadena, nombre) values (345, 'Hartmann-Fay');
insert into cadena (idCadena, nombre) values (346, 'Rodriguez and Sons');
insert into cadena (idCadena, nombre) values (347, 'Hauck and Sons');
insert into cadena (idCadena, nombre) values (348, 'Berge, Pagac and Cruickshank');
insert into cadena (idCadena, nombre) values (349, 'Kunde Inc');
insert into cadena (idCadena, nombre) values (350, 'Gutmann Inc');
insert into cadena (idCadena, nombre) values (351, 'Jones-Homenick');
insert into cadena (idCadena, nombre) values (352, 'Hyatt-Ortiz');
insert into cadena (idCadena, nombre) values (353, 'Medhurst LLC');
insert into cadena (idCadena, nombre) values (354, 'Olson Inc');
insert into cadena (idCadena, nombre) values (355, 'Hand-Torp');
insert into cadena (idCadena, nombre) values (356, 'Armstrong-Bashirian');
insert into cadena (idCadena, nombre) values (357, 'Hand-Kerluke');
insert into cadena (idCadena, nombre) values (358, 'Luettgen, Marks and Moore');
insert into cadena (idCadena, nombre) values (359, 'Kutch Group');
insert into cadena (idCadena, nombre) values (360, 'Sauer, Runte and Gorczany');
insert into cadena (idCadena, nombre) values (361, 'Roberts, Jenkins and Hammes');
insert into cadena (idCadena, nombre) values (362, 'Ward-Carter');
insert into cadena (idCadena, nombre) values (363, 'Rau-Ferry');
insert into cadena (idCadena, nombre) values (364, 'Turcotte-Ankunding');
insert into cadena (idCadena, nombre) values (365, 'Daugherty, Hodkiewicz and Reynolds');
insert into cadena (idCadena, nombre) values (366, 'Jacobson, Osinski and O''Conner');
insert into cadena (idCadena, nombre) values (367, 'Muller, Stokes and Schuppe');
insert into cadena (idCadena, nombre) values (368, 'Zboncak-Konopelski');
insert into cadena (idCadena, nombre) values (369, 'Johns Inc');
insert into cadena (idCadena, nombre) values (370, 'Johns, Bogisich and Padberg');
insert into cadena (idCadena, nombre) values (371, 'Toy LLC');
insert into cadena (idCadena, nombre) values (372, 'O''Kon, Glover and Pfannerstill');
insert into cadena (idCadena, nombre) values (373, 'Wyman, Cummings and Becker');
insert into cadena (idCadena, nombre) values (374, 'Reichel-Baumbach');
insert into cadena (idCadena, nombre) values (375, 'Parisian Inc');
insert into cadena (idCadena, nombre) values (376, 'Stark-Lang');
insert into cadena (idCadena, nombre) values (377, 'Heidenreich-Reichel');
insert into cadena (idCadena, nombre) values (378, 'Breitenberg-Stark');
insert into cadena (idCadena, nombre) values (379, 'Labadie Group');
insert into cadena (idCadena, nombre) values (380, 'Hoeger-Bartell');
insert into cadena (idCadena, nombre) values (381, 'Romaguera LLC');
insert into cadena (idCadena, nombre) values (382, 'Kiehn-Yost');
insert into cadena (idCadena, nombre) values (383, 'Heller-D''Amore');
insert into cadena (idCadena, nombre) values (384, 'Stamm, Reynolds and Zboncak');
insert into cadena (idCadena, nombre) values (385, 'Reynolds, Blick and Pacocha');
insert into cadena (idCadena, nombre) values (386, 'Kautzer-Davis');
insert into cadena (idCadena, nombre) values (387, 'Brakus and Sons');
insert into cadena (idCadena, nombre) values (388, 'Crist, Erdman and Nikolaus');
insert into cadena (idCadena, nombre) values (389, 'Flatley LLC');
insert into cadena (idCadena, nombre) values (390, 'Brakus, Medhurst and Haley');
insert into cadena (idCadena, nombre) values (391, 'Weissnat-Labadie');
insert into cadena (idCadena, nombre) values (392, 'Luettgen-Emard');
insert into cadena (idCadena, nombre) values (393, 'Considine-Nienow');
insert into cadena (idCadena, nombre) values (394, 'Lang, Grady and Johns');
insert into cadena (idCadena, nombre) values (395, 'Macejkovic-Schumm');
insert into cadena (idCadena, nombre) values (396, 'Hickle-Daugherty');
insert into cadena (idCadena, nombre) values (397, 'Gaylord LLC');
insert into cadena (idCadena, nombre) values (398, 'Stamm-Greenholt');
insert into cadena (idCadena, nombre) values (399, 'Feil Inc');
insert into cadena (idCadena, nombre) values (400, 'Feest, McGlynn and Pagac');
insert into cadena (idCadena, nombre) values (401, 'Kunde, Hermann and Prohaska');
insert into cadena (idCadena, nombre) values (402, 'Bailey Inc');
insert into cadena (idCadena, nombre) values (403, 'Kiehn-Rosenbaum');
insert into cadena (idCadena, nombre) values (404, 'Goodwin, Ledner and Kemmer');
insert into cadena (idCadena, nombre) values (405, 'Tremblay-Koch');
insert into cadena (idCadena, nombre) values (406, 'Price and Sons');
insert into cadena (idCadena, nombre) values (407, 'Emmerich-Dare');
insert into cadena (idCadena, nombre) values (408, 'Kunde-Dach');
insert into cadena (idCadena, nombre) values (409, 'Abernathy Inc');
insert into cadena (idCadena, nombre) values (410, 'Boyer, Heller and Schmeler');
insert into cadena (idCadena, nombre) values (411, 'Moen-Johns');
insert into cadena (idCadena, nombre) values (412, 'Cremin-Hyatt');
insert into cadena (idCadena, nombre) values (413, 'Howe LLC');
insert into cadena (idCadena, nombre) values (414, 'Braun and Sons');
insert into cadena (idCadena, nombre) values (415, 'Stracke LLC');
insert into cadena (idCadena, nombre) values (416, 'Schmeler, Reynolds and Corwin');
insert into cadena (idCadena, nombre) values (417, 'McDermott, Emard and Buckridge');
insert into cadena (idCadena, nombre) values (418, 'Rolfson-Daniel');
insert into cadena (idCadena, nombre) values (419, 'Blick, Brakus and Johnston');
insert into cadena (idCadena, nombre) values (420, 'Beahan and Sons');
insert into cadena (idCadena, nombre) values (421, 'Schowalter-Gislason');
insert into cadena (idCadena, nombre) values (422, 'Osinski, Runte and Corkery');
insert into cadena (idCadena, nombre) values (423, 'O''Conner-O''Kon');
insert into cadena (idCadena, nombre) values (424, 'Lang-Collins');
insert into cadena (idCadena, nombre) values (425, 'Crist-Kiehn');
insert into cadena (idCadena, nombre) values (426, 'Kunze-West');
insert into cadena (idCadena, nombre) values (427, 'Hauck Group');
insert into cadena (idCadena, nombre) values (428, 'Lowe, Rogahn and Luettgen');
insert into cadena (idCadena, nombre) values (429, 'Heaney Group');
insert into cadena (idCadena, nombre) values (430, 'Metz and Sons');
insert into cadena (idCadena, nombre) values (431, 'Wunsch-Keeling');
insert into cadena (idCadena, nombre) values (432, 'Streich Group');
insert into cadena (idCadena, nombre) values (433, 'Ondricka-Ruecker');
insert into cadena (idCadena, nombre) values (434, 'Bauch Inc');
insert into cadena (idCadena, nombre) values (435, 'Heathcote, Simonis and Deckow');
insert into cadena (idCadena, nombre) values (436, 'Padberg Inc');
insert into cadena (idCadena, nombre) values (437, 'Beahan, Wunsch and Parisian');
insert into cadena (idCadena, nombre) values (438, 'Johns and Sons');
insert into cadena (idCadena, nombre) values (439, 'Runolfsdottir-Abshire');
insert into cadena (idCadena, nombre) values (440, 'Ebert, Ruecker and O''Kon');
insert into cadena (idCadena, nombre) values (441, 'Jerde, Strosin and Mosciski');
insert into cadena (idCadena, nombre) values (442, 'Gulgowski, Buckridge and Leffler');
insert into cadena (idCadena, nombre) values (443, 'Roob, Kreiger and Schinner');
insert into cadena (idCadena, nombre) values (444, 'Shanahan LLC');
insert into cadena (idCadena, nombre) values (445, 'Lakin Inc');
insert into cadena (idCadena, nombre) values (446, 'Mayert, Kozey and Simonis');
insert into cadena (idCadena, nombre) values (447, 'Brekke, Casper and Shanahan');
insert into cadena (idCadena, nombre) values (448, 'Breitenberg, Renner and Quitzon');
insert into cadena (idCadena, nombre) values (449, 'Legros, Breitenberg and Jaskolski');
insert into cadena (idCadena, nombre) values (450, 'Haag-Crist');
insert into cadena (idCadena, nombre) values (451, 'Adams, Nienow and Wehner');
insert into cadena (idCadena, nombre) values (452, 'Grady, Lindgren and Abernathy');
insert into cadena (idCadena, nombre) values (453, 'Daniel, Wehner and Skiles');
insert into cadena (idCadena, nombre) values (454, 'Koelpin LLC');
insert into cadena (idCadena, nombre) values (455, 'Grimes LLC');
insert into cadena (idCadena, nombre) values (456, 'McClure-Sporer');
insert into cadena (idCadena, nombre) values (457, 'Wiza Group');
insert into cadena (idCadena, nombre) values (458, 'Walter, Ratke and Ferry');
insert into cadena (idCadena, nombre) values (459, 'Leffler-Ortiz');
insert into cadena (idCadena, nombre) values (460, 'Rempel, Sipes and Wyman');
insert into cadena (idCadena, nombre) values (461, 'Crooks, Gutkowski and McLaughlin');
insert into cadena (idCadena, nombre) values (462, 'Frami-McDermott');
insert into cadena (idCadena, nombre) values (463, 'Hane LLC');
insert into cadena (idCadena, nombre) values (464, 'Wintheiser-VonRueden');
insert into cadena (idCadena, nombre) values (465, 'Streich, Runolfsdottir and Conn');
insert into cadena (idCadena, nombre) values (466, 'Lehner-Sporer');
insert into cadena (idCadena, nombre) values (467, 'Lynch, Bayer and Hintz');
insert into cadena (idCadena, nombre) values (468, 'Walker and Sons');
insert into cadena (idCadena, nombre) values (469, 'Ankunding LLC');
insert into cadena (idCadena, nombre) values (470, 'Metz Inc');
insert into cadena (idCadena, nombre) values (471, 'Reynolds, Hamill and Gibson');
insert into cadena (idCadena, nombre) values (472, 'Haley Inc');
insert into cadena (idCadena, nombre) values (473, 'Jones LLC');
insert into cadena (idCadena, nombre) values (474, 'Lindgren, Ebert and Effertz');
insert into cadena (idCadena, nombre) values (475, 'Hettinger LLC');
insert into cadena (idCadena, nombre) values (476, 'Balistreri, Pagac and Gorczany');
insert into cadena (idCadena, nombre) values (477, 'Kulas-Glover');
insert into cadena (idCadena, nombre) values (478, 'Crooks-Marvin');
insert into cadena (idCadena, nombre) values (479, 'Green, Kessler and Cremin');
insert into cadena (idCadena, nombre) values (480, 'Koelpin Group');
insert into cadena (idCadena, nombre) values (481, 'Haag-Paucek');
insert into cadena (idCadena, nombre) values (482, 'Willms LLC');
insert into cadena (idCadena, nombre) values (483, 'Wehner-Wintheiser');
insert into cadena (idCadena, nombre) values (484, 'Macejkovic, Klein and Raynor');
insert into cadena (idCadena, nombre) values (485, 'Considine-Hahn');
insert into cadena (idCadena, nombre) values (486, 'Stokes, Hagenes and Hilll');
insert into cadena (idCadena, nombre) values (487, 'Bergnaum, Littel and Leannon');
insert into cadena (idCadena, nombre) values (488, 'Boehm-Beatty');
insert into cadena (idCadena, nombre) values (489, 'Connelly-Stark');
insert into cadena (idCadena, nombre) values (490, 'Wintheiser Inc');
insert into cadena (idCadena, nombre) values (491, 'Langworth-Lakin');
insert into cadena (idCadena, nombre) values (492, 'Moen, Skiles and Gerlach');
insert into cadena (idCadena, nombre) values (493, 'Schaden, Lowe and Dickinson');
insert into cadena (idCadena, nombre) values (494, 'Donnelly, Wisoky and Jakubowski');
insert into cadena (idCadena, nombre) values (495, 'Cummings-Wehner');
insert into cadena (idCadena, nombre) values (496, 'Brown Inc');
insert into cadena (idCadena, nombre) values (497, 'Mills, Batz and Rodriguez');
insert into cadena (idCadena, nombre) values (498, 'Schmitt-Von');
insert into cadena (idCadena, nombre) values (499, 'Casper, Fahey and O''Keefe');
insert into cadena (idCadena, nombre) values (500, 'Friesen-Johnson');
insert into cadena (idCadena, nombre) values (501, 'Howe-McKenzie');
insert into cadena (idCadena, nombre) values (502, 'Sauer, Beahan and Gislason');
insert into cadena (idCadena, nombre) values (503, 'Bogan-Langosh');
insert into cadena (idCadena, nombre) values (504, 'Eichmann and Sons');
insert into cadena (idCadena, nombre) values (505, 'Veum-Swaniawski');
insert into cadena (idCadena, nombre) values (506, 'Murphy Inc');
insert into cadena (idCadena, nombre) values (507, 'Goyette LLC');
insert into cadena (idCadena, nombre) values (508, 'Bode-Padberg');
insert into cadena (idCadena, nombre) values (509, 'Treutel, Luettgen and Schumm');
insert into cadena (idCadena, nombre) values (510, 'Rosenbaum, Skiles and Gislason');
insert into cadena (idCadena, nombre) values (511, 'McCullough-Kautzer');
insert into cadena (idCadena, nombre) values (512, 'Kozey, Gorczany and Wintheiser');
insert into cadena (idCadena, nombre) values (513, 'Willms LLC');
insert into cadena (idCadena, nombre) values (514, 'Williamson-Kertzmann');
insert into cadena (idCadena, nombre) values (515, 'Fadel-Kuhn');
insert into cadena (idCadena, nombre) values (516, 'Lesch and Sons');
insert into cadena (idCadena, nombre) values (517, 'Kutch Inc');
insert into cadena (idCadena, nombre) values (518, 'Murray, Hirthe and Franecki');
insert into cadena (idCadena, nombre) values (519, 'Reynolds, Bergnaum and Feest');
insert into cadena (idCadena, nombre) values (520, 'Fritsch, Watsica and Kreiger');
insert into cadena (idCadena, nombre) values (521, 'Kiehn LLC');
insert into cadena (idCadena, nombre) values (522, 'Cartwright, Christiansen and McGlynn');
insert into cadena (idCadena, nombre) values (523, 'Lind-Rohan');
insert into cadena (idCadena, nombre) values (524, 'Armstrong and Sons');
insert into cadena (idCadena, nombre) values (525, 'Schmidt-Weber');
insert into cadena (idCadena, nombre) values (526, 'Koss-VonRueden');
insert into cadena (idCadena, nombre) values (527, 'Walsh and Sons');
insert into cadena (idCadena, nombre) values (528, 'Mante and Sons');
insert into cadena (idCadena, nombre) values (529, 'Cronin-Mohr');
insert into cadena (idCadena, nombre) values (530, 'Keebler-Wisozk');
insert into cadena (idCadena, nombre) values (531, 'Sauer and Sons');
insert into cadena (idCadena, nombre) values (532, 'Champlin-Olson');
insert into cadena (idCadena, nombre) values (533, 'Grimes-O''Hara');
insert into cadena (idCadena, nombre) values (534, 'Blick-Schinner');
insert into cadena (idCadena, nombre) values (535, 'Schinner-Pfannerstill');
insert into cadena (idCadena, nombre) values (536, 'Becker Group');
insert into cadena (idCadena, nombre) values (537, 'Sawayn, Corkery and Jones');
insert into cadena (idCadena, nombre) values (538, 'Denesik-Kerluke');
insert into cadena (idCadena, nombre) values (539, 'Hoppe-Hansen');
insert into cadena (idCadena, nombre) values (540, 'Hickle, Wunsch and Effertz');
insert into cadena (idCadena, nombre) values (541, 'Borer Inc');
insert into cadena (idCadena, nombre) values (542, 'Jast, Gulgowski and Volkman');
insert into cadena (idCadena, nombre) values (543, 'Anderson LLC');
insert into cadena (idCadena, nombre) values (544, 'Corwin Inc');
insert into cadena (idCadena, nombre) values (545, 'Mayert-Cronin');
insert into cadena (idCadena, nombre) values (546, 'Beer LLC');
insert into cadena (idCadena, nombre) values (547, 'Rippin, Hessel and Wiegand');
insert into cadena (idCadena, nombre) values (548, 'Beatty Inc');
insert into cadena (idCadena, nombre) values (549, 'Schmitt, Russel and Weber');
insert into cadena (idCadena, nombre) values (550, 'Wiegand and Sons');
insert into cadena (idCadena, nombre) values (551, 'Schumm-King');
insert into cadena (idCadena, nombre) values (552, 'Orn LLC');
insert into cadena (idCadena, nombre) values (553, 'Rowe-Hauck');
insert into cadena (idCadena, nombre) values (554, 'Wiza LLC');
insert into cadena (idCadena, nombre) values (555, 'Cummings-Treutel');
insert into cadena (idCadena, nombre) values (556, 'Kassulke-Mante');
insert into cadena (idCadena, nombre) values (557, 'Rutherford-Dietrich');
insert into cadena (idCadena, nombre) values (558, 'Schaefer, Keeling and Flatley');
insert into cadena (idCadena, nombre) values (559, 'Bechtelar, Torp and Buckridge');
insert into cadena (idCadena, nombre) values (560, 'Zboncak LLC');
insert into cadena (idCadena, nombre) values (561, 'Lockman-Reinger');
insert into cadena (idCadena, nombre) values (562, 'Anderson-Mayert');
insert into cadena (idCadena, nombre) values (563, 'Sanford Group');
insert into cadena (idCadena, nombre) values (564, 'Langosh, Reichel and Zulauf');
insert into cadena (idCadena, nombre) values (565, 'Hackett Inc');
insert into cadena (idCadena, nombre) values (566, 'Bahringer-Kunde');
insert into cadena (idCadena, nombre) values (567, 'O''Reilly-Ebert');
insert into cadena (idCadena, nombre) values (568, 'Ullrich-Dare');
insert into cadena (idCadena, nombre) values (569, 'Corkery, Hermann and Bednar');
insert into cadena (idCadena, nombre) values (570, 'Shanahan, Heller and Wilderman');
insert into cadena (idCadena, nombre) values (571, 'Boyle, McLaughlin and Johnson');
insert into cadena (idCadena, nombre) values (572, 'McGlynn LLC');
insert into cadena (idCadena, nombre) values (573, 'Steuber-Tremblay');
insert into cadena (idCadena, nombre) values (574, 'Lowe, Bartoletti and Johnston');
insert into cadena (idCadena, nombre) values (575, 'Wolf, Gerhold and Langosh');
insert into cadena (idCadena, nombre) values (576, 'Yundt Group');
insert into cadena (idCadena, nombre) values (577, 'Haag-Schmitt');
insert into cadena (idCadena, nombre) values (578, 'Ledner-O''Connell');
insert into cadena (idCadena, nombre) values (579, 'Brown-Lynch');
insert into cadena (idCadena, nombre) values (580, 'O''Keefe Group');
insert into cadena (idCadena, nombre) values (581, 'Dare and Sons');
insert into cadena (idCadena, nombre) values (582, 'Schimmel Group');
insert into cadena (idCadena, nombre) values (583, 'Sporer-Waters');
insert into cadena (idCadena, nombre) values (584, 'Hettinger-Erdman');
insert into cadena (idCadena, nombre) values (585, 'Kiehn-Sanford');
insert into cadena (idCadena, nombre) values (586, 'Huels-McGlynn');
insert into cadena (idCadena, nombre) values (587, 'Brakus, Prosacco and Steuber');
insert into cadena (idCadena, nombre) values (588, 'Gorczany-Fadel');
insert into cadena (idCadena, nombre) values (589, 'Hansen-Schiller');
insert into cadena (idCadena, nombre) values (590, 'Nolan, Toy and Haley');
insert into cadena (idCadena, nombre) values (591, 'Treutel-Auer');
insert into cadena (idCadena, nombre) values (592, 'Marvin, Cummings and O''Kon');
insert into cadena (idCadena, nombre) values (593, 'Nicolas-Williamson');
insert into cadena (idCadena, nombre) values (594, 'Bosco Inc');
insert into cadena (idCadena, nombre) values (595, 'Spencer, Corkery and Lockman');
insert into cadena (idCadena, nombre) values (596, 'Kuphal-Johnston');
insert into cadena (idCadena, nombre) values (597, 'Gislason-Purdy');
insert into cadena (idCadena, nombre) values (598, 'Harris LLC');
insert into cadena (idCadena, nombre) values (599, 'O''Kon Inc');
insert into cadena (idCadena, nombre) values (600, 'Carroll, Balistreri and Lubowitz');
insert into cadena (idCadena, nombre) values (601, 'Dibbert-Cummerata');
insert into cadena (idCadena, nombre) values (602, 'D''Amore-Skiles');
insert into cadena (idCadena, nombre) values (603, 'Barton, Hirthe and Marquardt');
insert into cadena (idCadena, nombre) values (604, 'Lind-Larson');
insert into cadena (idCadena, nombre) values (605, 'Schoen LLC');
insert into cadena (idCadena, nombre) values (606, 'Kiehn, Rath and McKenzie');
insert into cadena (idCadena, nombre) values (607, 'Maggio Group');
insert into cadena (idCadena, nombre) values (608, 'King Inc');
insert into cadena (idCadena, nombre) values (609, 'Feeney-Sipes');
insert into cadena (idCadena, nombre) values (610, 'Boyer LLC');
insert into cadena (idCadena, nombre) values (611, 'Considine LLC');
insert into cadena (idCadena, nombre) values (612, 'Cole and Sons');
insert into cadena (idCadena, nombre) values (613, 'Vandervort Group');
insert into cadena (idCadena, nombre) values (614, 'Cormier and Sons');
insert into cadena (idCadena, nombre) values (615, 'Powlowski and Sons');
insert into cadena (idCadena, nombre) values (616, 'Reinger and Sons');
insert into cadena (idCadena, nombre) values (617, 'Kirlin, Nitzsche and Huels');
insert into cadena (idCadena, nombre) values (618, 'Marvin, Cummings and Kassulke');
insert into cadena (idCadena, nombre) values (619, 'Lakin-Ritchie');
insert into cadena (idCadena, nombre) values (620, 'Gerlach Inc');
insert into cadena (idCadena, nombre) values (621, 'Beier Group');
insert into cadena (idCadena, nombre) values (622, 'Feeney-Bruen');
insert into cadena (idCadena, nombre) values (623, 'Conn-Fay');
insert into cadena (idCadena, nombre) values (624, 'Predovic, McClure and Auer');
insert into cadena (idCadena, nombre) values (625, 'Kassulke-Satterfield');
insert into cadena (idCadena, nombre) values (626, 'Douglas, Quitzon and Walker');
insert into cadena (idCadena, nombre) values (627, 'Gerlach, Kovacek and Daniel');
insert into cadena (idCadena, nombre) values (628, 'Herzog-Satterfield');
insert into cadena (idCadena, nombre) values (629, 'Watsica-Keebler');
insert into cadena (idCadena, nombre) values (630, 'Daugherty Group');
insert into cadena (idCadena, nombre) values (631, 'Cremin-Ebert');
insert into cadena (idCadena, nombre) values (632, 'McDermott Group');
insert into cadena (idCadena, nombre) values (633, 'Nader LLC');
insert into cadena (idCadena, nombre) values (634, 'Torphy, Hegmann and Kemmer');
insert into cadena (idCadena, nombre) values (635, 'Smitham Inc');
insert into cadena (idCadena, nombre) values (636, 'Lind-Ruecker');
insert into cadena (idCadena, nombre) values (637, 'Hills, Altenwerth and Lindgren');
insert into cadena (idCadena, nombre) values (638, 'O''Conner Inc');
insert into cadena (idCadena, nombre) values (639, 'Tromp and Sons');
insert into cadena (idCadena, nombre) values (640, 'Abbott, Abernathy and Hansen');
insert into cadena (idCadena, nombre) values (641, 'Wolff Group');
insert into cadena (idCadena, nombre) values (642, 'Kutch and Sons');
insert into cadena (idCadena, nombre) values (643, 'Connelly, Kuphal and Rowe');
insert into cadena (idCadena, nombre) values (644, 'Leuschke-Rohan');
insert into cadena (idCadena, nombre) values (645, 'Miller Inc');
insert into cadena (idCadena, nombre) values (646, 'Leffler and Sons');
insert into cadena (idCadena, nombre) values (647, 'Cartwright Inc');
insert into cadena (idCadena, nombre) values (648, 'Yost, Hermann and Heaney');
insert into cadena (idCadena, nombre) values (649, 'Kreiger-Block');
insert into cadena (idCadena, nombre) values (650, 'Hayes-Stoltenberg');
insert into cadena (idCadena, nombre) values (651, 'Bradtke, McLaughlin and Batz');
insert into cadena (idCadena, nombre) values (652, 'Heller-Turner');
insert into cadena (idCadena, nombre) values (653, 'Jast Group');
insert into cadena (idCadena, nombre) values (654, 'Cummings Inc');
insert into cadena (idCadena, nombre) values (655, 'D''Amore-Hammes');
insert into cadena (idCadena, nombre) values (656, 'Fisher, Kassulke and Pfeffer');
insert into cadena (idCadena, nombre) values (657, 'Rempel-O''Kon');
insert into cadena (idCadena, nombre) values (658, 'Von-Corkery');
insert into cadena (idCadena, nombre) values (659, 'Rempel, Jaskolski and Shields');
insert into cadena (idCadena, nombre) values (660, 'Hermiston Group');
insert into cadena (idCadena, nombre) values (661, 'Predovic-Graham');
insert into cadena (idCadena, nombre) values (662, 'Roob Group');
insert into cadena (idCadena, nombre) values (663, 'Langosh, Ward and Hills');
insert into cadena (idCadena, nombre) values (664, 'Ondricka LLC');
insert into cadena (idCadena, nombre) values (665, 'Block Group');
insert into cadena (idCadena, nombre) values (666, 'Kozey, Auer and Cummerata');
insert into cadena (idCadena, nombre) values (667, 'Gerlach, Gerhold and Hahn');
insert into cadena (idCadena, nombre) values (668, 'Bernhard, Spinka and Bartoletti');
insert into cadena (idCadena, nombre) values (669, 'Daniel-Zieme');
insert into cadena (idCadena, nombre) values (670, 'Wehner LLC');
insert into cadena (idCadena, nombre) values (671, 'Lesch-Boyer');
insert into cadena (idCadena, nombre) values (672, 'Dicki and Sons');
insert into cadena (idCadena, nombre) values (673, 'Johnston and Sons');
insert into cadena (idCadena, nombre) values (674, 'West-Stoltenberg');
insert into cadena (idCadena, nombre) values (675, 'Feil Inc');
insert into cadena (idCadena, nombre) values (676, 'Mante, Baumbach and Ebert');
insert into cadena (idCadena, nombre) values (677, 'Erdman-Wisoky');
insert into cadena (idCadena, nombre) values (678, 'Hilll-Koelpin');
insert into cadena (idCadena, nombre) values (679, 'Rowe LLC');
insert into cadena (idCadena, nombre) values (680, 'Braun, Schaden and Grant');
insert into cadena (idCadena, nombre) values (681, 'Dickinson and Sons');
insert into cadena (idCadena, nombre) values (682, 'Macejkovic Group');
insert into cadena (idCadena, nombre) values (683, 'Luettgen-Collier');
insert into cadena (idCadena, nombre) values (684, 'Pfeffer, Satterfield and Bode');
insert into cadena (idCadena, nombre) values (685, 'Rodriguez Group');
insert into cadena (idCadena, nombre) values (686, 'Legros, Walter and Lind');
insert into cadena (idCadena, nombre) values (687, 'Schimmel-Fritsch');
insert into cadena (idCadena, nombre) values (688, 'Rogahn-Nader');
insert into cadena (idCadena, nombre) values (689, 'Strosin-Donnelly');
insert into cadena (idCadena, nombre) values (690, 'Breitenberg and Sons');
insert into cadena (idCadena, nombre) values (691, 'Rowe, Conn and Ebert');
insert into cadena (idCadena, nombre) values (692, 'Grady Group');
insert into cadena (idCadena, nombre) values (693, 'Schuster Group');
insert into cadena (idCadena, nombre) values (694, 'Considine-Bailey');
insert into cadena (idCadena, nombre) values (695, 'Cartwright-Tromp');
insert into cadena (idCadena, nombre) values (696, 'Romaguera, Hane and Marquardt');
insert into cadena (idCadena, nombre) values (697, 'Miller Inc');
insert into cadena (idCadena, nombre) values (698, 'Schiller, Rath and Zieme');
insert into cadena (idCadena, nombre) values (699, 'Dach, Koelpin and Hilll');
insert into cadena (idCadena, nombre) values (700, 'Doyle, Beahan and Goodwin');
insert into cadena (idCadena, nombre) values (701, 'Hauck-Collins');
insert into cadena (idCadena, nombre) values (702, 'Carroll, Lowe and Armstrong');
insert into cadena (idCadena, nombre) values (703, 'Kuhic, Bogisich and Baumbach');
insert into cadena (idCadena, nombre) values (704, 'Kihn, Goldner and Effertz');
insert into cadena (idCadena, nombre) values (705, 'Keeling-Mitchell');
insert into cadena (idCadena, nombre) values (706, 'Effertz Group');
insert into cadena (idCadena, nombre) values (707, 'Waelchi LLC');
insert into cadena (idCadena, nombre) values (708, 'Conn-Mante');
insert into cadena (idCadena, nombre) values (709, 'Ankunding, Balistreri and Pouros');
insert into cadena (idCadena, nombre) values (710, 'Rogahn Group');
insert into cadena (idCadena, nombre) values (711, 'Rodriguez Group');
insert into cadena (idCadena, nombre) values (712, 'Robel-Hauck');
insert into cadena (idCadena, nombre) values (713, 'Gleichner, Mraz and Larkin');
insert into cadena (idCadena, nombre) values (714, 'Nicolas-Skiles');
insert into cadena (idCadena, nombre) values (715, 'Lindgren Group');
insert into cadena (idCadena, nombre) values (716, 'Watsica LLC');
insert into cadena (idCadena, nombre) values (717, 'Reinger and Sons');
insert into cadena (idCadena, nombre) values (718, 'Bradtke, Johns and Rosenbaum');
insert into cadena (idCadena, nombre) values (719, 'Corkery, Considine and Purdy');
insert into cadena (idCadena, nombre) values (720, 'Schmidt and Sons');
insert into cadena (idCadena, nombre) values (721, 'O''Connell Inc');
insert into cadena (idCadena, nombre) values (722, 'Hagenes, Reichel and Medhurst');
insert into cadena (idCadena, nombre) values (723, 'Schmitt, Grimes and Beier');
insert into cadena (idCadena, nombre) values (724, 'Blanda-Klocko');
insert into cadena (idCadena, nombre) values (725, 'Mueller, Dietrich and Doyle');
insert into cadena (idCadena, nombre) values (726, 'Gottlieb, Powlowski and Bogisich');
insert into cadena (idCadena, nombre) values (727, 'Morar, Mosciski and Langworth');
insert into cadena (idCadena, nombre) values (728, 'Blick-Wisoky');
insert into cadena (idCadena, nombre) values (729, 'Toy, Stoltenberg and Lockman');
insert into cadena (idCadena, nombre) values (730, 'Yost-Corkery');
insert into cadena (idCadena, nombre) values (731, 'Murray-Mertz');
insert into cadena (idCadena, nombre) values (732, 'Torp, Powlowski and Orn');
insert into cadena (idCadena, nombre) values (733, 'Bogisich Inc');
insert into cadena (idCadena, nombre) values (734, 'Predovic, Little and Bernhard');
insert into cadena (idCadena, nombre) values (735, 'Dach-Breitenberg');
insert into cadena (idCadena, nombre) values (736, 'Stokes Inc');
insert into cadena (idCadena, nombre) values (737, 'Kunze-Beer');
insert into cadena (idCadena, nombre) values (738, 'Zemlak, Leuschke and Schaden');
insert into cadena (idCadena, nombre) values (739, 'Klocko, Osinski and Kulas');
insert into cadena (idCadena, nombre) values (740, 'Conn Inc');
insert into cadena (idCadena, nombre) values (741, 'Farrell-Jerde');
insert into cadena (idCadena, nombre) values (742, 'Batz Inc');
insert into cadena (idCadena, nombre) values (743, 'Will-Kreiger');
insert into cadena (idCadena, nombre) values (744, 'McCullough LLC');
insert into cadena (idCadena, nombre) values (745, 'Nicolas Group');
insert into cadena (idCadena, nombre) values (746, 'Goodwin, Stoltenberg and Lowe');
insert into cadena (idCadena, nombre) values (747, 'Harris and Sons');
insert into cadena (idCadena, nombre) values (748, 'Zboncak-Friesen');
insert into cadena (idCadena, nombre) values (749, 'Schneider, Haley and Sanford');
insert into cadena (idCadena, nombre) values (750, 'Schumm, Kub and Kirlin');
insert into cadena (idCadena, nombre) values (751, 'Rohan, Halvorson and Kassulke');
insert into cadena (idCadena, nombre) values (752, 'Toy, Kiehn and Reinger');
insert into cadena (idCadena, nombre) values (753, 'Farrell, O''Reilly and Mueller');
insert into cadena (idCadena, nombre) values (754, 'Borer LLC');
insert into cadena (idCadena, nombre) values (755, 'Marquardt LLC');
insert into cadena (idCadena, nombre) values (756, 'Boyle, Crona and Moen');
insert into cadena (idCadena, nombre) values (757, 'Robel-Pollich');
insert into cadena (idCadena, nombre) values (758, 'Langosh, Bashirian and Huels');
insert into cadena (idCadena, nombre) values (759, 'Schowalter, Doyle and Cassin');
insert into cadena (idCadena, nombre) values (760, 'Will Group');
insert into cadena (idCadena, nombre) values (761, 'Witting, Metz and Sanford');
insert into cadena (idCadena, nombre) values (762, 'Hilll, Huel and Ferry');
insert into cadena (idCadena, nombre) values (763, 'Champlin, Kilback and Anderson');
insert into cadena (idCadena, nombre) values (764, 'Fisher-Kassulke');
insert into cadena (idCadena, nombre) values (765, 'Sporer, Kihn and Kuhlman');
insert into cadena (idCadena, nombre) values (766, 'Okuneva Inc');
insert into cadena (idCadena, nombre) values (767, 'McLaughlin-Sawayn');
insert into cadena (idCadena, nombre) values (768, 'Feeney-Muller');
insert into cadena (idCadena, nombre) values (769, 'Moen and Sons');
insert into cadena (idCadena, nombre) values (770, 'Kihn-Mohr');
insert into cadena (idCadena, nombre) values (771, 'Howe-Waelchi');
insert into cadena (idCadena, nombre) values (772, 'Waters-Kertzmann');
insert into cadena (idCadena, nombre) values (773, 'Kovacek-Lindgren');
insert into cadena (idCadena, nombre) values (774, 'Koss-Von');
insert into cadena (idCadena, nombre) values (775, 'Swaniawski-Jacobi');
insert into cadena (idCadena, nombre) values (776, 'Pacocha, Murazik and Aufderhar');
insert into cadena (idCadena, nombre) values (777, 'Johnston, Feeney and Kautzer');
insert into cadena (idCadena, nombre) values (778, 'Weber-Rodriguez');
insert into cadena (idCadena, nombre) values (779, 'Muller-Prosacco');
insert into cadena (idCadena, nombre) values (780, 'Hilpert, Champlin and Langworth');
insert into cadena (idCadena, nombre) values (781, 'Walker Group');
insert into cadena (idCadena, nombre) values (782, 'Schoen and Sons');
insert into cadena (idCadena, nombre) values (783, 'Beatty and Sons');
insert into cadena (idCadena, nombre) values (784, 'Hettinger and Sons');
insert into cadena (idCadena, nombre) values (785, 'Brown, Haag and Olson');
insert into cadena (idCadena, nombre) values (786, 'Douglas-Batz');
insert into cadena (idCadena, nombre) values (787, 'Pfeffer-Hahn');
insert into cadena (idCadena, nombre) values (788, 'Abbott-O''Keefe');
insert into cadena (idCadena, nombre) values (789, 'Kassulke, Bashirian and Friesen');
insert into cadena (idCadena, nombre) values (790, 'Kris, Feil and Quigley');
insert into cadena (idCadena, nombre) values (791, 'Labadie-Sauer');
insert into cadena (idCadena, nombre) values (792, 'Hayes, Stokes and Torp');
insert into cadena (idCadena, nombre) values (793, 'Purdy, Leffler and Rippin');
insert into cadena (idCadena, nombre) values (794, 'Wintheiser, Gulgowski and Kling');
insert into cadena (idCadena, nombre) values (795, 'Roberts and Sons');
insert into cadena (idCadena, nombre) values (796, 'Morissette Group');
insert into cadena (idCadena, nombre) values (797, 'Berge Inc');
insert into cadena (idCadena, nombre) values (798, 'Hickle and Sons');
insert into cadena (idCadena, nombre) values (799, 'Toy, Mohr and Hansen');
insert into cadena (idCadena, nombre) values (800, 'Hoeger Group');
insert into cadena (idCadena, nombre) values (801, 'Kuvalis, Monahan and Beahan');
insert into cadena (idCadena, nombre) values (802, 'Tillman, Toy and Leannon');
insert into cadena (idCadena, nombre) values (803, 'Collins LLC');
insert into cadena (idCadena, nombre) values (804, 'Grimes, Crona and Weimann');
insert into cadena (idCadena, nombre) values (805, 'Will-Kshlerin');
insert into cadena (idCadena, nombre) values (806, 'Bashirian and Sons');
insert into cadena (idCadena, nombre) values (807, 'Aufderhar, Stracke and Toy');
insert into cadena (idCadena, nombre) values (808, 'Glover LLC');
insert into cadena (idCadena, nombre) values (809, 'Reichel Group');
insert into cadena (idCadena, nombre) values (810, 'Ritchie, Wilderman and Keeling');
insert into cadena (idCadena, nombre) values (811, 'Hayes, Baumbach and Braun');
insert into cadena (idCadena, nombre) values (812, 'King Group');
insert into cadena (idCadena, nombre) values (813, 'Osinski-Barrows');
insert into cadena (idCadena, nombre) values (814, 'Walker, Ondricka and Hagenes');
insert into cadena (idCadena, nombre) values (815, 'Wolff Inc');
insert into cadena (idCadena, nombre) values (816, 'Cummerata, Considine and Baumbach');
insert into cadena (idCadena, nombre) values (817, 'Hirthe and Sons');
insert into cadena (idCadena, nombre) values (818, 'Hessel and Sons');
insert into cadena (idCadena, nombre) values (819, 'Kuhn-Hodkiewicz');
insert into cadena (idCadena, nombre) values (820, 'Cole Inc');
insert into cadena (idCadena, nombre) values (821, 'Reynolds Inc');
insert into cadena (idCadena, nombre) values (822, 'Kunze, Rosenbaum and Leuschke');
insert into cadena (idCadena, nombre) values (823, 'Bartoletti LLC');
insert into cadena (idCadena, nombre) values (824, 'Dickinson-Leuschke');
insert into cadena (idCadena, nombre) values (825, 'Gottlieb and Sons');
insert into cadena (idCadena, nombre) values (826, 'Murray-Denesik');
insert into cadena (idCadena, nombre) values (827, 'Pollich-Conroy');
insert into cadena (idCadena, nombre) values (828, 'McKenzie Group');
insert into cadena (idCadena, nombre) values (829, 'Kautzer Group');
insert into cadena (idCadena, nombre) values (830, 'Kovacek-Beer');
insert into cadena (idCadena, nombre) values (831, 'Russel-Jast');
insert into cadena (idCadena, nombre) values (832, 'Emmerich, Kuhlman and Beier');
insert into cadena (idCadena, nombre) values (833, 'Hickle-Oberbrunner');
insert into cadena (idCadena, nombre) values (834, 'Gerhold and Sons');
insert into cadena (idCadena, nombre) values (835, 'Botsford, Wuckert and Feeney');
insert into cadena (idCadena, nombre) values (836, 'Kertzmann LLC');
insert into cadena (idCadena, nombre) values (837, 'Rolfson Inc');
insert into cadena (idCadena, nombre) values (838, 'Price, Denesik and Treutel');
insert into cadena (idCadena, nombre) values (839, 'Kessler, Kuhn and Langosh');
insert into cadena (idCadena, nombre) values (840, 'Cremin Inc');
insert into cadena (idCadena, nombre) values (841, 'Spinka-Adams');
insert into cadena (idCadena, nombre) values (842, 'Howe LLC');
insert into cadena (idCadena, nombre) values (843, 'Fadel Group');
insert into cadena (idCadena, nombre) values (844, 'Price Group');
insert into cadena (idCadena, nombre) values (845, 'McCullough, Wiegand and Bode');
insert into cadena (idCadena, nombre) values (846, 'Schmidt and Sons');
insert into cadena (idCadena, nombre) values (847, 'Goldner, Frami and Strosin');
insert into cadena (idCadena, nombre) values (848, 'Baumbach, Jast and Kulas');
insert into cadena (idCadena, nombre) values (849, 'Bayer, Hilll and Abbott');
insert into cadena (idCadena, nombre) values (850, 'Miller and Sons');
insert into cadena (idCadena, nombre) values (851, 'Roberts LLC');
insert into cadena (idCadena, nombre) values (852, 'Hilpert-Pfannerstill');
insert into cadena (idCadena, nombre) values (853, 'McGlynn, Reinger and Runolfsson');
insert into cadena (idCadena, nombre) values (854, 'King, Gerlach and Haley');
insert into cadena (idCadena, nombre) values (855, 'Shanahan, Pollich and Schowalter');
insert into cadena (idCadena, nombre) values (856, 'Kilback Inc');
insert into cadena (idCadena, nombre) values (857, 'Huels Group');
insert into cadena (idCadena, nombre) values (858, 'Volkman, Kirlin and Nikolaus');
insert into cadena (idCadena, nombre) values (859, 'Von, Blanda and Torp');
insert into cadena (idCadena, nombre) values (860, 'Bauch, Block and Muller');
insert into cadena (idCadena, nombre) values (861, 'Schaden-McGlynn');
insert into cadena (idCadena, nombre) values (862, 'Crooks, Spencer and Williamson');
insert into cadena (idCadena, nombre) values (863, 'Fahey LLC');
insert into cadena (idCadena, nombre) values (864, 'Connelly-Harvey');
insert into cadena (idCadena, nombre) values (865, 'Stanton, VonRueden and Graham');
insert into cadena (idCadena, nombre) values (866, 'Cole, MacGyver and Ernser');
insert into cadena (idCadena, nombre) values (867, 'Quitzon-Witting');
insert into cadena (idCadena, nombre) values (868, 'Kirlin and Sons');
insert into cadena (idCadena, nombre) values (869, 'Stoltenberg-Bailey');
insert into cadena (idCadena, nombre) values (870, 'Wintheiser-Reichert');
insert into cadena (idCadena, nombre) values (871, 'Larson, Robel and Kreiger');
insert into cadena (idCadena, nombre) values (872, 'Aufderhar, Lubowitz and Beier');
insert into cadena (idCadena, nombre) values (873, 'Sipes, Cummings and Crist');
insert into cadena (idCadena, nombre) values (874, 'Hills-Weissnat');
insert into cadena (idCadena, nombre) values (875, 'Boyle-Powlowski');
insert into cadena (idCadena, nombre) values (876, 'Brown Inc');
insert into cadena (idCadena, nombre) values (877, 'Daniel-Lakin');
insert into cadena (idCadena, nombre) values (878, 'Klocko-Klocko');
insert into cadena (idCadena, nombre) values (879, 'Yost-Halvorson');
insert into cadena (idCadena, nombre) values (880, 'D''Amore, Farrell and Vandervort');
insert into cadena (idCadena, nombre) values (881, 'Balistreri, Becker and Mraz');
insert into cadena (idCadena, nombre) values (882, 'Hegmann Inc');
insert into cadena (idCadena, nombre) values (883, 'Rath-Hayes');
insert into cadena (idCadena, nombre) values (884, 'Padberg LLC');
insert into cadena (idCadena, nombre) values (885, 'Orn-Harber');
insert into cadena (idCadena, nombre) values (886, 'O''Reilly-Gutkowski');
insert into cadena (idCadena, nombre) values (887, 'Bergnaum Inc');
insert into cadena (idCadena, nombre) values (888, 'Stoltenberg Group');
insert into cadena (idCadena, nombre) values (889, 'Gleichner-Keeling');
insert into cadena (idCadena, nombre) values (890, 'Green-Wolf');
insert into cadena (idCadena, nombre) values (891, 'Conn, Kshlerin and Klein');
insert into cadena (idCadena, nombre) values (892, 'Gerhold-Morissette');
insert into cadena (idCadena, nombre) values (893, 'Bergnaum, Schaefer and Kling');
insert into cadena (idCadena, nombre) values (894, 'Reilly-Homenick');
insert into cadena (idCadena, nombre) values (895, 'Hirthe-Dietrich');
insert into cadena (idCadena, nombre) values (896, 'Mann and Sons');
insert into cadena (idCadena, nombre) values (897, 'Glover-Blanda');
insert into cadena (idCadena, nombre) values (898, 'Kshlerin and Sons');
insert into cadena (idCadena, nombre) values (899, 'Schneider-Kertzmann');
insert into cadena (idCadena, nombre) values (900, 'Feeney, Berge and Bernier');
insert into cadena (idCadena, nombre) values (901, 'Lueilwitz-Bogan');
insert into cadena (idCadena, nombre) values (902, 'Skiles and Sons');
insert into cadena (idCadena, nombre) values (903, 'McLaughlin and Sons');
insert into cadena (idCadena, nombre) values (904, 'Mertz-Jerde');
insert into cadena (idCadena, nombre) values (905, 'Schmitt Group');
insert into cadena (idCadena, nombre) values (906, 'Wuckert, Cole and Langosh');
insert into cadena (idCadena, nombre) values (907, 'Kuvalis-Rippin');
insert into cadena (idCadena, nombre) values (908, 'Effertz-Wolff');
insert into cadena (idCadena, nombre) values (909, 'Herman, Pollich and Ratke');
insert into cadena (idCadena, nombre) values (910, 'Kuphal, Breitenberg and Runolfsson');
insert into cadena (idCadena, nombre) values (911, 'Schultz LLC');
insert into cadena (idCadena, nombre) values (912, 'Lemke-Buckridge');
insert into cadena (idCadena, nombre) values (913, 'Prohaska Group');
insert into cadena (idCadena, nombre) values (914, 'Wiegand, Mertz and Quitzon');
insert into cadena (idCadena, nombre) values (915, 'Green LLC');
insert into cadena (idCadena, nombre) values (916, 'Windler-Larkin');
insert into cadena (idCadena, nombre) values (917, 'Gorczany, Hilpert and Runte');
insert into cadena (idCadena, nombre) values (918, 'Willms Inc');
insert into cadena (idCadena, nombre) values (919, 'Klocko, Kihn and Quitzon');
insert into cadena (idCadena, nombre) values (920, 'Brown-Schaden');
insert into cadena (idCadena, nombre) values (921, 'Raynor and Sons');
insert into cadena (idCadena, nombre) values (922, 'Paucek Group');
insert into cadena (idCadena, nombre) values (923, 'Ernser, Koepp and Greenfelder');
insert into cadena (idCadena, nombre) values (924, 'Predovic-Glover');
insert into cadena (idCadena, nombre) values (925, 'Windler-Upton');
insert into cadena (idCadena, nombre) values (926, 'Gutmann-Metz');
insert into cadena (idCadena, nombre) values (927, 'Jast, Bernhard and Effertz');
insert into cadena (idCadena, nombre) values (928, 'Erdman-Leannon');
insert into cadena (idCadena, nombre) values (929, 'Bauch, Ullrich and Ledner');
insert into cadena (idCadena, nombre) values (930, 'Rowe, Greenfelder and Quigley');
insert into cadena (idCadena, nombre) values (931, 'Steuber Inc');
insert into cadena (idCadena, nombre) values (932, 'O''Kon Inc');
insert into cadena (idCadena, nombre) values (933, 'Hermann, Reinger and Rowe');
insert into cadena (idCadena, nombre) values (934, 'Ward, Haley and Zboncak');
insert into cadena (idCadena, nombre) values (935, 'Dickens LLC');
insert into cadena (idCadena, nombre) values (936, 'Bailey and Sons');
insert into cadena (idCadena, nombre) values (937, 'Casper Group');
insert into cadena (idCadena, nombre) values (938, 'Lemke, Stamm and Lehner');
insert into cadena (idCadena, nombre) values (939, 'Larson, Robel and Koepp');
insert into cadena (idCadena, nombre) values (940, 'Kris-Lebsack');
insert into cadena (idCadena, nombre) values (941, 'Hackett-Bosco');
insert into cadena (idCadena, nombre) values (942, 'Ebert-Bednar');
insert into cadena (idCadena, nombre) values (943, 'Macejkovic LLC');
insert into cadena (idCadena, nombre) values (944, 'Kemmer-Hoeger');
insert into cadena (idCadena, nombre) values (945, 'Gerhold-Towne');
insert into cadena (idCadena, nombre) values (946, 'Bartell LLC');
insert into cadena (idCadena, nombre) values (947, 'Runolfsdottir Group');
insert into cadena (idCadena, nombre) values (948, 'Skiles-Grant');
insert into cadena (idCadena, nombre) values (949, 'Weber LLC');
insert into cadena (idCadena, nombre) values (950, 'Reinger-Cummerata');
insert into cadena (idCadena, nombre) values (951, 'Kuhlman LLC');
insert into cadena (idCadena, nombre) values (952, 'Herzog-Marquardt');
insert into cadena (idCadena, nombre) values (953, 'Boyle and Sons');
insert into cadena (idCadena, nombre) values (954, 'Miller Inc');
insert into cadena (idCadena, nombre) values (955, 'Krajcik, Hilpert and Glover');
insert into cadena (idCadena, nombre) values (956, 'Reynolds-Raynor');
insert into cadena (idCadena, nombre) values (957, 'Schroeder, Pfeffer and Olson');
insert into cadena (idCadena, nombre) values (958, 'Ankunding Group');
insert into cadena (idCadena, nombre) values (959, 'Farrell LLC');
insert into cadena (idCadena, nombre) values (960, 'Ullrich-Beatty');
insert into cadena (idCadena, nombre) values (961, 'Kulas-Rau');
insert into cadena (idCadena, nombre) values (962, 'Bartoletti-Crist');
insert into cadena (idCadena, nombre) values (963, 'Hyatt LLC');
insert into cadena (idCadena, nombre) values (964, 'Barrows, Gerhold and Schneider');
insert into cadena (idCadena, nombre) values (965, 'Senger, Goyette and Haag');
insert into cadena (idCadena, nombre) values (966, 'Stamm Group');
insert into cadena (idCadena, nombre) values (967, 'Mraz-VonRueden');
insert into cadena (idCadena, nombre) values (968, 'Robel, Jerde and Kiehn');
insert into cadena (idCadena, nombre) values (969, 'Gaylord, Swift and Beer');
insert into cadena (idCadena, nombre) values (970, 'Rippin, Prosacco and Heathcote');
insert into cadena (idCadena, nombre) values (971, 'Steuber-Kohler');
insert into cadena (idCadena, nombre) values (972, 'Walker, Schuster and Waelchi');
insert into cadena (idCadena, nombre) values (973, 'Mann Inc');
insert into cadena (idCadena, nombre) values (974, 'Koch, Stamm and Langworth');
insert into cadena (idCadena, nombre) values (975, 'Ullrich, Altenwerth and Schmidt');
insert into cadena (idCadena, nombre) values (976, 'Mosciski Inc');
insert into cadena (idCadena, nombre) values (977, 'Bernhard Inc');
insert into cadena (idCadena, nombre) values (978, 'Pfannerstill-Feeney');
insert into cadena (idCadena, nombre) values (979, 'Kihn, Streich and Hilpert');
insert into cadena (idCadena, nombre) values (980, 'Herzog-Koepp');
insert into cadena (idCadena, nombre) values (981, 'Wilderman and Sons');
insert into cadena (idCadena, nombre) values (982, 'Thiel, Harris and Bogisich');
insert into cadena (idCadena, nombre) values (983, 'Smith LLC');
insert into cadena (idCadena, nombre) values (984, 'Torp-Boyer');
insert into cadena (idCadena, nombre) values (985, 'Heidenreich and Sons');
insert into cadena (idCadena, nombre) values (986, 'Stamm-Kutch');
insert into cadena (idCadena, nombre) values (987, 'Kirlin, Gorczany and O''Keefe');
insert into cadena (idCadena, nombre) values (988, 'Cremin-Kemmer');
insert into cadena (idCadena, nombre) values (989, 'Purdy Group');
insert into cadena (idCadena, nombre) values (990, 'Zemlak-Terry');
insert into cadena (idCadena, nombre) values (991, 'Schumm, Streich and McClure');
insert into cadena (idCadena, nombre) values (992, 'Rutherford Group');
insert into cadena (idCadena, nombre) values (993, 'Sporer and Sons');
insert into cadena (idCadena, nombre) values (994, 'Shanahan-Wintheiser');
insert into cadena (idCadena, nombre) values (995, 'Prosacco Group');
insert into cadena (idCadena, nombre) values (996, 'Reynolds and Sons');
insert into cadena (idCadena, nombre) values (997, 'Nienow LLC');
insert into cadena (idCadena, nombre) values (998, 'Conroy, Kertzmann and Lehner');
insert into cadena (idCadena, nombre) values (999, 'Borer, Mertz and Boyle');
insert into cadena (idCadena, nombre) values (1000, 'Swift-Jacobi');
