ALTER TABLE Rate 
ADD CONSTRAINT OCCUP PRIMARY KEY(occupancy,room_type) ;

ALTER TABLE Room_type 
ADD CONSTRAINT PK_room_type PRIMARY KEY(id) ;

ALTER TABLE Room 
ADD CONSTRAINT PK_room PRIMARY KEY(id) ;

ALTER TABLE Guest ADD CONSTRAINT PK_guest PRIMARY KEY(id) ;

ALTER TABLE Booking ADD CONSTRAINT PK_booking PRIMARY KEY(booking_id);

ALTER TABLE Extra ADD CONSTRAINT PK_extra PRIMARY KEY(extra_id);